/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:09 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <QuartzCore/CAAnimationDelegate-Protocol.h>
#import <MPUFoundation/MPUMarqueeViewDelegate-Protocol.h>

@interface MPUMarqueeView : UIView <CAAnimationDelegate> {

	NSUUID* _currentAnimationID;
	NSInteger _options;
	NSPointerArray* _coordinatedMarqueeViews;
	MPUMarqueeView* _primaryMarqueeView;
	BOOL _marqueeEnabled;
	CGFloat _contentGap;
	UIView* _contentView;
	id<MPUMarqueeViewDelegate> _delegate;
	CGFloat _marqueeDelay;
	CGFloat _marqueeScrollRate;
	UIView* _viewForContentSize;
	CGSize _contentSize;
	UIEdgeInsets _fadeEdgeInsets;

}

@property (assign,nonatomic) CGFloat contentGap;                                        //@synthesize contentGap=_contentGap - In the implementation block
@property (assign,nonatomic) CGSize contentSize;                                       //@synthesize contentSize=_contentSize - In the implementation block
@property (nonatomic,readonly) UIView * contentView;                                   //@synthesize contentView=_contentView - In the implementation block
@property (assign,nonatomic) UIEdgeInsets fadeEdgeInsets;                              //@synthesize fadeEdgeInsets=_fadeEdgeInsets - In the implementation block
@property (assign,nonatomic) id<MPUMarqueeViewDelegate> delegate;               //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) CGFloat marqueeDelay;                                      //@synthesize marqueeDelay=_marqueeDelay - In the implementation block
@property (assign,nonatomic) CGFloat marqueeScrollRate;                                 //@synthesize marqueeScrollRate=_marqueeScrollRate - In the implementation block
@property (assign,getter=isMarqueeEnabled,nonatomic) BOOL marqueeEnabled;              //@synthesize marqueeEnabled=_marqueeEnabled - In the implementation block
@property (nonatomic,readonly) NSArray * coordinatedMarqueeViews; 
@property (nonatomic,retain) UIView * viewForContentSize;                              //@synthesize viewForContentSize=_viewForContentSize - In the implementation block
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setFrame:(CGRect)arg1 ;
-(CGSize)contentSize;
-(void)layoutSubviews;
-(UIView *)contentView;
-(void)setContentSize:(CGSize)arg1 ;
-(void)setDelegate:(id<MPUMarqueeViewDelegate>)arg1 ;
-(void)didMoveToWindow;
-(void)invalidateIntrinsicContentSize;
-(void)setBounds:(CGRect)arg1 ;
-(id<MPUMarqueeViewDelegate>)delegate;
-(CGFloat)_duration;
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2 ;
-(CGSize)intrinsicContentSize;
-(UIView *)viewForLastBaselineLayout;
-(void)setMarqueeEnabled:(BOOL)arg1 ;
-(UIView *)viewForFirstBaselineLayout;
-(void)_createMarqueeAnimationIfNeeded;
-(void)_tearDownMarqueeAnimation;
-(void)_applyMarqueeFade;
-(void)addCoordinatedMarqueeView:(id)arg1 ;
-(void)_createMarqueeAnimationIfNeededWithMaximumDuration:(CGFloat)arg1 beginTime:(CGFloat)arg2 ;
-(void)setMarqueeDelay:(CGFloat)arg1 ;
-(void)setMarqueeScrollRate:(CGFloat)arg1 ;
-(void)setViewForContentSize:(UIView *)arg1 ;
-(NSArray *)coordinatedMarqueeViews;
-(CGFloat)contentGap;
-(UIEdgeInsets)fadeEdgeInsets;
-(CGFloat)marqueeDelay;
-(CGFloat)marqueeScrollRate;
-(UIView *)viewForContentSize;
-(void)setContentGap:(CGFloat)arg1 ;
-(BOOL)isMarqueeEnabled;
-(void)setMarqueeEnabled:(BOOL)arg1 withOptions:(NSInteger)arg2 ;
-(void)resetMarqueePosition;
-(void)setFadeEdgeInsets:(UIEdgeInsets)arg1 ;
@end
