#import <ControlCenterUI/CCUIControlCenterSectionViewControllerDelegate-Protocol.h>

@interface CCUISystemControlsPageViewController : UIViewController <CCUIControlCenterSectionViewControllerDelegate>
@end