/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:20 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/CCUIButtonSectionController.h>
#import <ControlCenterUI/CCUIButtonStackPagingView.h>

@interface CCUISettingsSectionController : CCUIButtonSectionController
@property (nonatomic, retain) CCUIButtonStackPagingView *view;
@property (nonatomic,readonly) BOOL usesCompactHeight; 
+(Class)buttonControllerClass;
-(id)settings;
-(void)viewWillAppear:(BOOL)arg1 ;
-(id)sectionIdentifier;
-(BOOL)usesCompactHeight;
-(BOOL)buttonControllerShouldUseSmallButtons:(id)arg1 ;
@end
