/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:20 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <ControlCenterUI/CCUIControlCenterSectionView.h>
#import <ControlCenterUI/CCUIButtonStackLayoutDelegate-Protocol.h>
#import <ControlCenterUI/CCUIButtonStackPagingViewDelegate-Protocol.h>
#import <ControlCenterUI/CCUIImmediateTouchScrollView.h>

@interface CCUIButtonStackPagingView : CCUIControlCenterSectionView <CCUIButtonStackLayoutDelegate, UIScrollViewDelegate> {

	NSMutableArray* _buttons;
	CCUIImmediateTouchScrollView* _scrollView;
	UIStackView* _pagesStackView;
	NSUInteger _buttonStretchThreshold;
	NSLayoutConstraint* _topMargin;
	NSLayoutConstraint* _bottomMargin;
	NSLayoutConstraint* _leadingMargin;
	NSLayoutConstraint* _trailingMargin;
	NSUInteger _maxButtonsPerPage;
	NSInteger _axis;
	CGFloat _interButtonPadding;
	id<CCUIButtonStackPagingViewDelegate> _delegate;

}

@property (assign,nonatomic) CGFloat interButtonPadding;                                          //@synthesize interButtonPadding=_interButtonPadding - In the implementation block
@property (assign,nonatomic) UIEdgeInsets marginInsets; 
@property (assign,nonatomic) NSInteger axis;                                                     //@synthesize axis=_axis - In the implementation block
@property (assign,nonatomic) NSInteger pagingAxis; 
@property (assign,nonatomic) NSUInteger buttonStretchThreshold;                          //@synthesize buttonStretchThreshold=_buttonStretchThreshold - In the implementation block
@property (assign,nonatomic) NSUInteger maxButtonsPerPage;                               //@synthesize maxButtonsPerPage=_maxButtonsPerPage - In the implementation block
@property (assign,nonatomic) id<CCUIButtonStackPagingViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSArray * buttons; 
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<CCUIButtonStackPagingViewDelegate>)arg1 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(id<CCUIButtonStackPagingViewDelegate>)delegate;
-(NSInteger)axis;
-(void)setAxis:(NSInteger)arg1 ;
-(NSArray *)buttons;
-(void)addButton:(id)arg1 ;
-(void)setButtons:(NSArray *)arg1 ;
-(UIEdgeInsets)marginInsets;
-(void)setMarginInsets:(UIEdgeInsets)arg1 ;
-(void)resortButtons;
-(void)removeButton:(id)arg1 ;
-(void)scrollToPage:(NSUInteger)arg1 animated:(BOOL)arg2 ;
-(void)_organizeButtonsInPages;
-(void)_applyConfigurationToButtonStacks;
-(id)_primaryButtons;
-(id)_internalButtons;
-(void)setInterButtonPadding:(CGFloat)arg1 ;
-(void)setButtonStretchThreshold:(NSUInteger)arg1 ;
-(void)buttonStack:(id)arg1 didLayoutWithSpacing:(CGFloat)arg2 ;
-(void)setMaxButtonsPerPage:(NSUInteger)arg1 ;
-(void)setPagingAxis:(NSInteger)arg1 ;
-(NSInteger)pagingAxis;
-(NSUInteger)maxButtonsPerPage;
-(NSUInteger)buttonStretchThreshold;
-(CGFloat)interButtonPadding;
@end
