/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:21 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <ControlCenterUI/CCUIControlCenterObserver-Protocol.h>
#import <ControlCenterUI/CCUIControlCenterSectionViewControllerDelegate-Protocol.h>

@interface CCUIControlCenterSectionViewController : UIViewController <CCUIControlCenterObserver> {

	id<CCUIControlCenterSectionViewControllerDelegate> _delegate;

}

@property (assign,nonatomic) id<CCUIControlCenterSectionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy,readonly) NSString * sectionIdentifier; 
@property (readonly) NSUInteger hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(Class)viewClass;
-(BOOL)enabled;
-(void)setDelegate:(id<CCUIControlCenterSectionViewControllerDelegate>)arg1 ;
-(id<CCUIControlCenterSectionViewControllerDelegate>)delegate;
-(id)view;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(NSString *)sectionIdentifier;
-(id)controlCenterSystemAgent;
-(BOOL)dismissModalFullScreenIfNeeded;
-(void)controlCenterWillPresent;
-(void)controlCenterDidDismiss;
-(void)controlCenterWillBeginTransition;
-(void)controlCenterDidFinishTransition;
@end
