/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:16 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <MPUFoundation/MPUMarqueeView.h>

@interface MPUNowPlayingMetadataView : UIView {

	MPUMarqueeView* _marqueeView;
	UILabel* _label;
	UIButton* _button;
	BOOL _marqueeEnabled;
	NSAttributedString* _attributedText;
	NSUInteger _numberOfLines;

}

@property (nonatomic,copy) NSAttributedString * attributedText;                //@synthesize attributedText=_attributedText - In the implementation block
@property (assign,nonatomic) NSUInteger numberOfLines;                 //@synthesize numberOfLines=_numberOfLines - In the implementation block
@property (assign,nonatomic) BOOL marqueeEnabled;                              //@synthesize marqueeEnabled=_marqueeEnabled - In the implementation block
@property (nonatomic,readonly) CGFloat firstBaselineOffsetFromTop; 
@property (nonatomic,readonly) CGFloat baselineOffsetFromBottom; 
+(Class)labelClass;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)addTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(NSUInteger)arg3 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setNumberOfLines:(NSUInteger)arg1 ;
-(void)setAttributedText:(NSAttributedString *)arg1 ;
-(NSAttributedString *)attributedText;
-(void)removeTarget:(id)arg1 action:(SEL)arg2 forControlEvents:(NSUInteger)arg3 ;
-(UILabel *)label;
-(NSUInteger)numberOfLines;
-(void)setMarqueeEnabled:(BOOL)arg1 ;
-(BOOL)marqueeEnabled;
-(CGFloat)baselineOffsetFromBottom;
-(void)_touchControlActivate:(id)arg1 ;
-(void)_touchControlDeactivate:(id)arg1 ;
-(CGFloat)firstBaselineOffsetFromTop;
@end
