/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:20 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import "CCUIControlCenterPageContentViewControllerDelegate-Protocol.h"
@protocol CCUIControlCenterSectionViewControllerDelegate
@required
-(NSInteger)layoutStyle;
-(void)noteSectionEnabledStateDidChange:(id)arg1;
-(void)section:(id)arg1 publishStatusUpdate:(id)arg2;
-(void)sectionWantsControlCenterDismissal:(id)arg1;
-(id)controlCenterSystemAgent;
-(void)beginSuppressingPunchOutMaskCachingForReason:(id)arg1;
-(void)endSuppressingPunchOutMaskCachingForReason:(id)arg1;
- (id<CCUIControlCenterPageContentViewControllerDelegate>)delegate;

@end
