//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CCUIControlCenterButton;
#import <SpringBoard/CCUIControlCenterSystemAgent-Protocol.h>

@protocol CCUIControlCenterButtonDelegate 
- (id <CCUIControlCenterSystemAgent>)controlCenterSystemAgent;
- (BOOL)isInternal;
- (void)buttonTapped:(CCUIControlCenterButton *)arg1;

@optional
- (void)button:(CCUIControlCenterButton *)arg1 didChangeState:(NSInteger)arg2;
@end

