/*
* This header is generated by classdump-dyld 0.7
* on Sunday, July 5, 2015 at 9:41:29 PM Eastern Daylight Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /System/Library/PrivateFrameworks/MusicLibrary.framework/MusicLibrary
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <MusicLibrary/MusicLibrary-Structs.h>
#import <MusicLibrary/ML3Entity.h>

@class ML3Predicate, NSString, NSArray;

@interface ML3Container : ML3Entity

@property (readonly) ML3Predicate * staticPredicate; 
@property (readonly) ML3Predicate * dynamicPredicate; 
@property (getter=isLimitedByCount,readonly) char limitedByCount; 
@property (getter=isLimitOrderingDescending,readonly) char limitOrderingDescending; 
@property (copy,readonly) NSString * limitingProperty; 
@property (copy,readonly) NSArray * limitOrderingTerms; 
@property (readonly) long long limitValue; 
@property (copy,readonly) NSArray * cloudDisplayOrderingTerms; 
@property (copy,readonly) NSArray * displayOrderingTerms; 
+(id)propertyForMPMediaEntityProperty:(id)arg1 ;
+(void)initialize;
+(int)revisionTrackingCode;
+(id)persistentIDColumnForTable:(id)arg1 ;
+(id)joinClausesForProperty:(id)arg1 ;
+(id)foreignDatabaseTableForProperty:(id)arg1 ;
+(id)foreignColumnForProperty:(id)arg1 ;
+(id)databaseTable;
+(char)libraryContentsChangeForProperty:(id)arg1 ;
+(char)libraryDynamicChangeForProperty:(id)arg1 ;
+(id)extraTablesToDelete;
+(char)deleteFromLibrary:(id)arg1 deletionType:(int)arg2 persistentIDs:(const long long*)arg3 count:(unsigned)arg4 ;
+(id)defaultFilterPredicates;
+(id)defaultOrderingTerms;
+(id)sectionPropertyForProperty:(id)arg1 ;
+(void)populateDynamicContainersInLibrary:(id)arg1 ;
+(void)populateStaticItemsOfDynamicContainersInLibrary:(id)arg1 ;
+(void)populateSortOrdersOfPropertyValues:(id)arg1 inLibrary:(id)arg2 cachedNameOrders:(id)arg3 ;
+(void)populateMediaTypesOfStaticContainersInLibrary:(id)arg1 ;
+(char)hasCriterionInCriteriaList:(SearchCriteriaListRef)arg1 forITDBTrackField:(int)arg2 ;
+(id)nextFilepathForPlaylistType:(int)arg1 withPersistentID:(unsigned long long)arg2 inLibrary:(id)arg3 ;
+(id)predicateForCriteriaList:(SearchCriteriaListRef)arg1 dynamicCriteria:(char)arg2 parentMatchedAny:(char)arg3 ;
+(void)_insertNewSmartPlaylist:(id)arg1 criteriaBlob:(id)arg2 evaluationOrder:(unsigned long)arg3 limited:(char)arg4 trackOrder:(unsigned long)arg5 distinguishedKind:(int)arg6 inLibrary:(id)arg7 cachedNameOrders:(id)arg8 ;
+(void)populateDynamicContainersWithTrackPersistentID:(id)arg1 inLibrary:(id)arg2 createBuiltinSmartPlaylists:(char)arg3 ;
+(void)populateDynamicContainersWithTrackPersistentID:(id)arg1 inLibrary:(id)arg2 createBuiltinSmartPlaylists:(char)arg3 usingConnection:(id)arg4 ;
+(char)createMissingBuiltInSmartPlaylists:(id)arg1 ;
+(id)__mediaTypesForTracksWithDatabaseConnection:(id)arg1 tracksPersistentIDsEnumerationBlock:(/*^block*/id)arg2 ;
+(void)_updateContainedMediaTypeInContainerWithPersistentID:(long long)arg1 connection:(id)arg2 itemUpdateBlock:(/*^block*/id)arg3 ;
+(void)_clearContainerMediaTypeInContainerWithPersistentID:(long long)arg1 connection:(id)arg2 ;
+(id)_mediaTypesForTracksInContainerWithPersistentID:(long long)arg1 connection:(id)arg2 ;
+(void)_addMediaTypesToContainerWithPersistentID:(long long)arg1 mediaTypes:(id)arg2 connection:(id)arg3 ;
+(void)reloadContainedMediaTypesForContainerWithPersistID:(long long)arg1 connection:(id)arg2 ;
+(void)_removeMediaTypesFromContainerWithPersistentID:(long long)arg1 mediaTypes:(id)arg2 connection:(id)arg3 ;
+(id)_mediaTypesForTracksWithSwappedPersistentIDsInArray:(id)arg1 connection:(id)arg2 ;
+(id)_mediaTypesForTracksWithSwappedPersistentIDs:(const long long*)arg1 count:(int)arg2 connection:(id)arg3 ;
+(char)smartCriteriaCanBeEvaluated:(id)arg1 ;
+(char)updateBuiltInSmartPlaylistNamesForCurrentLanguage:(id)arg1 ;
+(id)autoCreatedBuiltInSmartPlaylistsPIDs:(id)arg1 ;
+(void)deleteAutoCreatedBuiltInSmartPlaylistsPIDs:(id)arg1 inLibrary:(id)arg2 ;
+(void)populateDynamicContainersInLibrary:(id)arg1 createBuiltinSmartPlaylists:(char)arg2 ;
+(void)populateDynamicContainersWithTrackPersistentID:(id)arg1 inLibrary:(id)arg2 ;
+(int)protocolSortTypeFromTrackOrder:(unsigned long)arg1 ;
+(unsigned long)trackOrderFromProtocolSortType:(int)arg1 ;
-(id)initWithDictionary:(id)arg1 inLibrary:(id)arg2 cachedNameOrders:(id)arg3 usingConnection:(id)arg4 ;
-(void)setValues:(id)arg1 forProperties:(id)arg2 async:(char)arg3 withCompletionBlock:(/*^block*/id)arg4 ;
-(void)_setContainerSeedItemPersistentIDValue:(id)arg1 ;
-(SearchCriteriaListRef)importedCriteriaList;
-(char)isEvaluationOrderingDescending;
-(char)isLimitOrderingDescending;
-(NSArray *)limitOrderingTerms;
-(id)evaluationOrderingTerms;
-(ML3Predicate *)staticPredicate;
-(id)populateSQLWithStaticTrackPersistentID:(id)arg1 ;
-(id)populateStatementParametersWithStaticTrackPersistentID:(id)arg1 ;
-(char)setTracksWithPersistentIDs:(const long long*)arg1 count:(unsigned)arg2 ;
-(char)setContainsTrack:(char)arg1 forPersistentID:(long long)arg2 notify:(char)arg3 ;
-(char)_setSwappedItemPersistentIDs:(const long long*)arg1 reloadContainedMediaTypes:(char)arg2 mediaTypesToRemove:(id)arg3 mediaTypesToAdd:(id)arg4 size:(int)arg5 notify:(char)arg6 ;
-(char)_setSwappedItemPersistentIDs:(const long long*)arg1 reloadContainedMediaTypes:(char)arg2 size:(int)arg3 notify:(char)arg4 ;
-(char)removeTracksAtIndexes:(id)arg1 notify:(char)arg2 ;
-(void)_accessCurrentSwappedPersisentIDsUsingBlock:(/*^block*/id)arg1 ;
-(char)_setSwappedItemPersistentIDs:(const long long*)arg1 mediaTypesToRemove:(id)arg2 mediaTypesToAdd:(id)arg3 size:(int)arg4 notify:(char)arg5 ;
-(char)addTracksWithPersistentIDs:(long long*)arg1 count:(unsigned)arg2 notify:(char)arg3 ;
-(char)removeTracksAtIndexes:(id)arg1 notify:(char)arg2 indexesTransformBlock:(/*^block*/id)arg3 ;
-(char)addTracksWithPersistentIDs:(long long*)arg1 count:(unsigned)arg2 ;
-(char)_setSwappedItemPersistentIDs:(const long long*)arg1 reloadContainedMediaTypes:(char)arg2 size:(int)arg3 ;
-(char)setTracksWithPersistentIDs:(const long long*)arg1 count:(unsigned)arg2 notify:(char)arg3 ;
-(ML3Predicate *)dynamicPredicate;
-(char)isLimitedByCount;
-(NSString *)limitingProperty;
-(long long)limitValue;
-(NSArray *)cloudDisplayOrderingTerms;
-(NSArray *)displayOrderingTerms;
-(char)removeAllTracks;
-(char)removeFirstTrack;
-(char)removeTracksAtIndexes:(id)arg1 ;
-(char)removeTracksWithPersistentIDs:(const long long*)arg1 atFilteredIndexes:(id)arg2 ;
-(char)addTrackWithPersistentID:(long long)arg1 ;
-(char)moveTrackFromIndex:(unsigned)arg1 toIndex:(unsigned)arg2 ;
-(char)setTracksWithSwappedPersistentIDData:(id)arg1 ;
-(id)trackPersistentIds;
-(id)childPlaylistPersistentIds;
-(char)isBuiltInSmartPlaylist;
-(id)multiverseIdentifier;
-(id)protocolItem;
-(id)_criteriaListDescription:(SearchCriteriaListRef)arg1 level:(int)arg2 ;
-(id)_stringForCriterionMatchKey:(SCD_Struct_ML10*)arg1 ;
-(id)_stringForCriterionMatchType:(SCD_Struct_ML10*)arg1 ;
-(id)_stringForCriterionBuffer:(SCD_Struct_ML10*)arg1 ;
-(id)_addUnitesForCriterionInfo:(SCD_Struct_ML10*)arg1 ;
-(id)_booleanStringForCriteriaInfo:(SCD_Struct_ML10*)arg1 ;
-(id)_stringForTrackFieldMediaKind:(long long)arg1 ;
-(id)_stringForTrackFieldCloudStatus:(long long)arg1 ;
-(id)_convertNumericValueFromCriterionMatchKey:(unsigned long)arg1 criteriaValue:(long long)arg2 ;
-(id)_formatTime:(long long)arg1 ;
-(id)_stringStringForCriteriaInfo:(SCD_Struct_ML10*)arg1 ;
-(id)_numericStringForCriteriaInfo:(SCD_Struct_ML10*)arg1 ;
-(id)_nonzeroStringForCriteriaInfo:(SCD_Struct_ML10*)arg1 ;
-(id)_dateStringForCriteriaInfo:(SCD_Struct_ML10*)arg1 ;
-(id)criteriaListDescription;
@end

