/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:21 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import "CCUIControlCenterSectionView.h"
#import <ControlCenterUI/CCUIControlCenterPushButton.h>

@interface CCUIButtonLikeSectionSplitView : CCUIControlCenterSectionView {

	CGFloat _separatorWidth;
	NSUInteger _mode;
	CCUIControlCenterPushButton* _leftSection;
	CCUIControlCenterPushButton* _rightSection;

}

@property (assign,nonatomic) NSUInteger mode;                                 //@synthesize mode=_mode - In the implementation block
@property (nonatomic,retain) CCUIControlCenterPushButton * leftSection;               //@synthesize leftSection=_leftSection - In the implementation block
@property (nonatomic,retain) CCUIControlCenterPushButton * rightSection;              //@synthesize rightSection=_rightSection - In the implementation block
@property (nonatomic,retain) CCUIControlCenterPushButton * middleSection;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
-(void)setMode:(NSUInteger)arg1 ;
-(NSUInteger)mode;
-(void)setLeftSection:(CCUIControlCenterPushButton *)arg1 ;
-(void)setRightSection:(CCUIControlCenterPushButton *)arg1 ;
-(CCUIControlCenterPushButton *)leftSection;
-(CCUIControlCenterPushButton *)rightSection;
-(void)_updateLabelParameters;
-(void)_updateButtonsCorners;
-(void)_relayout;
-(UIEdgeInsets)_landscapeInsetsForSection;
-(CGRect)_frameForSectionSlot:(int)arg1 ;
-(CCUIControlCenterPushButton *)_viewForSectionSlot:(int)arg1 ;
- (void)test3Buttons;
@end
