include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = pop
pop_FILES = $(wildcard *.mm) WebCore/TransformationMatrix.cpp
pop_INSTALL_PATH = /Library/Frameworks

include $(THEOS_MAKE_PATH)/framework.mk
