//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ControlCenterUI/CCUIControlCenterObserver-Protocol.h>
#import <ControlCenterUI/CCUIControlCenterPageContentViewControllerDelegate-Protocol.h>

@protocol CCUIControlCenterPageContentViewControllerDelegate;

@protocol CCUIControlCenterPageContentProviding <CCUIControlCenterObserver>
@property(nonatomic) id <CCUIControlCenterPageContentViewControllerDelegate> delegate;

@optional
@property(readonly, nonatomic) BOOL wantsVisible;
@property(readonly, nonatomic) UIEdgeInsets contentInsets;
- (void)controlCenterDidScrollToThisPage:(BOOL)arg1;
- (BOOL)dismissModalFullScreenIfNeeded;
- (CGFloat)requestedPageHeightForHeight:(CGFloat)height;
@end

