/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:16 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <MediaPlayerUI/MPAVRoute.h>

@interface MPUAVRouteHeaderLabel : UIView {

	NSAttributedString* _primaryLabelAttributedText;
	NSAttributedString* _secondaryLabelAttributedText;
	BOOL _animating;
	BOOL _needsAttributedTextReload;
	BOOL _nextAttributedTextReloadShouldAnimate;
	BOOL _showNowPlayingText;
	BOOL _showPendingText;
	UILabel* _primaryLabel;
	UILabel* _secondaryLabel;
	MPAVRoute* _route;
	UIColor* _primaryTextColor;
	UIColor* _secondaryTextColor;

}

@property (nonatomic,readonly) UILabel * primaryLabel;                       //@synthesize primaryLabel=_primaryLabel - In the implementation block
@property (nonatomic,readonly) UILabel * secondaryLabel;                     //@synthesize secondaryLabel=_secondaryLabel - In the implementation block
@property (nonatomic,readonly) CGFloat baselineOffsetFromBottom; 
@property (nonatomic,retain) MPAVRoute * route;                              //@synthesize route=_route - In the implementation block
@property (assign,nonatomic) BOOL showNowPlayingText;                        //@synthesize showNowPlayingText=_showNowPlayingText - In the implementation block
@property (assign,nonatomic) BOOL showPendingText;                           //@synthesize showPendingText=_showPendingText - In the implementation block
@property (nonatomic,retain) UIColor * primaryTextColor;                     //@synthesize primaryTextColor=_primaryTextColor - In the implementation block
@property (nonatomic,retain) UIColor * secondaryTextColor;                   //@synthesize secondaryTextColor=_secondaryTextColor - In the implementation block
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)_init;
-(CGFloat)baselineOffsetFromBottom;
-(UILabel *)secondaryLabel;
-(MPAVRoute *)route;
-(void)setRoute:(MPAVRoute *)arg1 ;
-(UIColor *)primaryTextColor;
-(void)setPrimaryTextColor:(UIColor *)arg1 ;
-(UIColor *)secondaryTextColor;
-(void)setSecondaryTextColor:(UIColor *)arg1 ;
-(void)_setNeedsAttributedTextReloadAnimated:(BOOL)arg1 ;
-(void)setShowNowPlayingText:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setShowPendingText:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)_labelAttributesUsingSecondaryStyle:(BOOL)arg1 ;
-(id)_currentDeviceConnectingText;
-(id)_currentDeviceLocalRoutingNowPlayingText;
-(void)_reloadAttributedTextAnimated:(BOOL)arg1 ;
-(id)_stateAwareAttributedTextForRoute:(id)arg1 usingSecondaryStyleForRouteName:(BOOL)arg2 orForNowPlayingText:(BOOL)arg3 ;
-(void)_getAttributedTextForPrimaryLabel:(id*)arg1 secondaryLabel:(id*)arg2 ;
-(void)setShowNowPlayingText:(BOOL)arg1 ;
-(void)setShowPendingText:(BOOL)arg1 ;
-(UILabel *)primaryLabel;
-(BOOL)showNowPlayingText;
-(BOOL)showPendingText;
@end
