// /*
// * This header is generated by classdump-dyld 1.0
// * on Tuesday, December 27, 2016 at 4:56:16 PM Japan Standard Time
// * Operating System: Version 10.1.1 (Build 14B150)
// * Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
// * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
// */

// #import <MediaPlayerUI/MPUNowPlayingDelegate-Protocol.h>
// #import <MediaPlayerUI/MPUNowPlayingMetadata.h>

// @interface MPUNowPlayingController : NSObject {

// 	NSDictionary* _currentNowPlayingInfo;
// 	CGFloat _currentElapsed;
// 	CGFloat _currentDuration;
// 	NSInteger _isPlaying;
// 	NSString* _currentNowPlayingAppDisplayID;
// 	BOOL _hasValidCurrentNowPlayingAppDisplayID;
// 	BOOL _isRegisteredForNowPlayingNotifications;
// 	BOOL _isUpdatingNowPlayingInfo;
// 	BOOL _isUpdatingPlaybackState;
// 	BOOL _isUpdatingNowPlayingApp;
// 	BOOL _wantsTimeInformationUpdates;
// 	UIImage* _cachedNowPlayingArtwork;
// 	BOOL _cachedArtworkDirty;
// 	BOOL _currentNowPlayingAppIsRunning;
// 	BOOL _shouldUpdateNowPlayingArtwork;
// 	id<MPUNowPlayingDelegate> _delegate;
// 	NSString* _currentNowPlayingArtworkDigest;
// 	CGFloat _timeInformationUpdateInterval;

// }

// @property (assign,nonatomic) id<MPUNowPlayingDelegate> delegate;                        //@synthesize delegate=_delegate - In the implementation block
// @property (nonatomic,readonly) NSDictionary * currentNowPlayingInfo; 
// @property (nonatomic,readonly) MPUNowPlayingMetadata * currentNowPlayingMetadata; 
// @property (nonatomic,readonly) UIImage * currentNowPlayingArtwork; 
// @property (nonatomic,readonly) NSString * currentNowPlayingArtworkDigest;                      //@synthesize currentNowPlayingArtworkDigest=_currentNowPlayingArtworkDigest - In the implementation block
// @property (nonatomic,readonly) BOOL isPlaying; 
// @property (nonatomic,readonly) NSString * nowPlayingAppDisplayID; 
// @property (nonatomic,readonly) BOOL currentNowPlayingAppIsRunning;                             //@synthesize currentNowPlayingAppIsRunning=_currentNowPlayingAppIsRunning - In the implementation block
// @property (nonatomic,readonly) BOOL nowPlayingAppIsSystemMediaApp; 
// @property (nonatomic,readonly) CGFloat currentElapsed;                                          //@synthesize currentElapsed=_currentElapsed - In the implementation block
// @property (nonatomic,readonly) CGFloat currentDuration; 
// @property (assign,nonatomic) CGFloat timeInformationUpdateInterval;                             //@synthesize timeInformationUpdateInterval=_timeInformationUpdateInterval - In the implementation block
// @property (assign,nonatomic) BOOL shouldUpdateNowPlayingArtwork;                               //@synthesize shouldUpdateNowPlayingArtwork=_shouldUpdateNowPlayingArtwork - In the implementation block
// -(void)_unregisterForNotifications;
// -(void)startUpdating;
// -(void)stopUpdating;
// -(id)init;
// -(void)setDelegate:(id<MPUNowPlayingDelegate>)arg1 ;
// // -(void)dealloc;
// -(id<MPUNowPlayingDelegate>)delegate;
// -(BOOL)isPlaying;
// -(void)update;
// -(BOOL)nowPlayingAppIsSystemMediaApp;
// -(MPUNowPlayingMetadata *)currentNowPlayingMetadata;
// -(NSString *)currentNowPlayingArtworkDigest;
// -(UIImage *)currentNowPlayingArtwork;
// -(BOOL)currentNowPlayingAppIsRunning;
// -(CGFloat)currentElapsed;
// -(void)_updateCurrentNowPlaying;
// -(NSDictionary *)currentNowPlayingInfo;
// -(void)_updatePlaybackState;
// -(void)_updateNowPlayingAppDisplayID;
// -(NSString *)nowPlayingAppDisplayID;
// -(void)_updateTimeInformationAndCallDelegate:(BOOL)arg1 ;
// -(BOOL)_isUpdatingTimeInformation;
// -(void)_stopUpdatingTimeInformation;
// -(void)_startUpdatingTimeInformation;
// -(void)setTimeInformationUpdateInterval:(CGFloat)arg1 ;
// -(CGFloat)timeInformationUpdateInterval;
// -(BOOL)shouldUpdateNowPlayingArtwork;
// -(void)setShouldUpdateNowPlayingArtwork:(BOOL)arg1 ;
// -(void)_registerForNotifications;
// -(CGFloat)currentDuration;
// @end
