/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:51:16 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MediaPlayerUI/MPVolumeControllerDelegate-Protocol.h>
#import <MediaPlayerUI/MPAVController.h>

@interface MPVolumeController : NSObject {

	MPAVController* _player;
	NSString* _volumeAudioCategory;
	BOOL _volumeWarningBlinking;
	UIImage* _volumeWarningTrackImage;
	BOOL _debugVolumeWarning;
	BOOL _volumeWarningEnabled;
	float _volumeValue;
	CGFloat _EUVolumeLimit;
	id<MPVolumeControllerDelegate> _delegate;
	NSInteger _volumeWarningState;

}

@property (assign,nonatomic) id<MPVolumeControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) float volumeValue;                                         //@synthesize volumeValue=_volumeValue - In the implementation block
@property (assign,nonatomic) BOOL muted; 
@property (nonatomic,retain) MPAVController * player; 
@property (nonatomic,copy) NSString * volumeAudioCategory; 
@property (nonatomic,readonly) BOOL volumeWarningEnabled;                                 //@synthesize volumeWarningEnabled=_volumeWarningEnabled - In the implementation block
@property (nonatomic,readonly) NSInteger volumeWarningState;                              //@synthesize volumeWarningState=_volumeWarningState - In the implementation block
@property (nonatomic,readonly) CGFloat EUVolumeLimit;                                       //@synthesize EUVolumeLimit=_EUVolumeLimit - In the implementation block
-(id)init;
-(void)setDelegate:(id<MPVolumeControllerDelegate>)arg1 ;
// -(void)dealloc;
-(id<MPVolumeControllerDelegate>)delegate;
-(void)_isExternalPlaybackActiveDidChangeNotification:(id)arg1 ;
-(BOOL)muted;
-(CGFloat)setVolumeValue:(float)arg1 ;
-(BOOL)volumeWarningEnabled;
-(NSInteger)volumeWarningState;
-(void)updateVolumeWarningState;
-(void)updateVolumeValue;
-(void)_availableRoutesDidChangeNotification:(id)arg1 ;
-(NSString *)volumeAudioCategory;
-(void)setVolumeAudioCategory:(NSString *)arg1 ;
-(CGFloat)EUVolumeLimit;
-(void)_mediaServerDiedNotification:(id)arg1 ;
-(void)_systemVolumeDidChange:(id)arg1 ;
-(void)_setupNotifications;
-(void)_tearDownNotifications;
-(CGFloat)_volumeFromAVController;
-(void)_setVolumeWarningState:(NSInteger)arg1 ;
-(float)volumeValue;
-(void)_internalSetVolumeValue:(CGFloat)arg1 ;
-(BOOL)_isPlayerInValidState;
-(void)_systemMuteDidChange:(id)arg1 ;
-(void)_EUVolumeLimitDidChange:(id)arg1 ;
-(void)_EUVolumeLimitEnforcedDidChange:(id)arg1 ;
-(void)_volumeDidChange:(id)arg1 ;
-(void)_forcefullySetVolumeValue:(CGFloat)arg1 ;
-(void)_applicationDidEnterBackgroundNotification:(id)arg1 ;
-(void)_applicationWillEnterForegroundNotification:(id)arg1 ;
-(MPAVController *)player;
-(void)setPlayer:(MPAVController *)arg1 ;
-(void)setMuted:(BOOL)arg1 ;
@end
