TOOL_NAME = rootHelper
rootHelper_INSTALL_PATH = /Library/Application Support/QuickCenter
rootHelper_OBJC_FILES = rootHelper.c

include $(THEOS)/makefiles/common.mk
include $(THEOS)/makefiles/tool.mk
