GO_EASY_ON_ME = 1

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = EyePatch
EyePatch_FILES = Tweak.xm
EyePatch_FRAMEWORKS = AVFoundation AudioToolbox CoreGraphics QuartzCore UIKit

include $(THEOS_MAKE_PATH)/tweak.mk

after-install::
	install.exec "killall -9 Periscope"



# Can you hear me in 5 secs?

# could you?

# How about Now?


# # Yay :) Gtg to finish this now