/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBRootIconListView.h"

@interface SBDockIconListView : SBRootIconListView
{
}

+ (NSUInteger)iconRowsForInterfaceOrientation:(NSInteger)arg1;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(NSInteger)arg1;
+ (CGFloat)defaultHeight;
- (NSUInteger)columnAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (CGFloat)_additionalSideInsetToCenterIcons;
- (NSUInteger)rowAtPoint:(struct CGPoint)arg1;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(NSUInteger *)arg2 proposedOrder:(int *)arg3 grabbedIcon:(id)arg4;
- (CGFloat)sideIconInset;
- (CGFloat)topIconInset;
- (NSUInteger)iconsInRowForSpacingCalculation;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (int)iconLocation;
- (id)initWithModel:(id)arg1 orientation:(NSInteger)arg2 viewMap:(id)arg3;

@end

