//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconAnimatorDelegate-Protocol.h"

@class NSMutableArray, NSString, SBFolderController, SBFolderControllerAnimationContext, SBIconAnimationSettings, UIView;

@interface SBIconAnimator : NSObject
{
    CGFloat _fraction;
    BOOL _startedAnimation;
    BOOL _startAnimationAfterRotationEnds;
    BOOL _windowIsRotating;
    BOOL _cleanedUp;
    NSMutableArray *_pendedAnimationContexts;
    SBFolderControllerAnimationContext *_animationContext;
    NSString *_instanceIdentifier;
    BOOL _invalidated;
    id <SBIconAnimatorDelegate> _delegate;
    SBIconAnimationSettings *_settings;
    SBFolderController *_folderController;
}

@property(readonly, nonatomic) SBFolderControllerAnimationContext *animationContext; // @synthesize animationContext=_animationContext;
@property(readonly, nonatomic) SBFolderController *folderController; // @synthesize folderController=_folderController;
@property(nonatomic) BOOL invalidated; // @synthesize invalidated=_invalidated;
@property(retain, nonatomic) SBIconAnimationSettings *settings; // @synthesize settings=_settings;
@property(nonatomic, assign) id <SBIconAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_windowFinishedRotating;
- (void)_invalidateCompletions;
- (void)_allowRotationOnMainWindowIfNecessary:(BOOL)arg1;
- (id)_centralAnimationFactory;
- (void)_animateToFraction:(CGFloat)arg1 afterDelay:(CGFloat)arg2 withSharedCompletion:(void*)arg3;
- (unsigned long long)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(CGFloat)arg1;
- (void)_prepareAnimation;
- (BOOL)_isDelayedForRotation;
- (void)_animateToFractionFromContext:(id)arg1;
- (void)_animateToFractionFromPendingContexts;
- (void)cleanup;
- (void)animateToFraction:(CGFloat)arg1 afterDelay:(CGFloat)arg2 withCompletion:(void*)arg3;
- (void)setFraction:(CGFloat)arg1;
- (void)prepare;
- (id)centralAnimationFactory;
@property(readonly, nonatomic) UIView *referenceView;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1;

@end

