//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, UIImage;

@interface SBIcon : NSObject <SBIconIndexNode>
{
    NSHashTable *_observers;
    id _badgeNumberOrString;
    unsigned int _uninstalled:1;
    UIImage *_cachedIconImages[14];
}

- (BOOL)canReceiveGrabbedIcon;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)uninstallAlertCancelTitle;
- (id)uninstallAlertConfirmTitle;
- (id)uninstallAlertBodyForAppWithDocumentUpdatesPending;
- (id)uninstallAlertBodyForAppWithDocumentsInCloud;
- (id)uninstallAlertBody;
- (id)uninstallAlertTitleForAppWithDocumentUpdatesPending;
- (id)uninstallAlertTitleForAppWithDocumentsInCloud;
- (id)uninstallAlertTitle;
- (BOOL)isUninstalled;
- (void)setUninstalled;
- (void)completeUninstall;
- (BOOL)allowsUninstall;
- (BOOL)shouldAnimateProgress;
- (BOOL)progressIsPaused;
- (double)progressPercent;
- (NSInteger)progressState;
- (void)launchFromLocation:(int)arg1;
- (id)automationID;
- (BOOL)isRecentlyUpdated;
- (void)setBadge:(id)arg1;
- (void)noteBadgeDidChange;
- (int)accessoryTypeForLocation:(int)arg1;
- (id)accessoryTextForLocation:(int)arg1;
- (id)badgeNumberOrString;
- (NSInteger)badgeValue;
- (void)reloadIconImagePurgingImageCache:(BOOL)arg1;
- (void)reloadIconImage;
- (void)purgeCachedImages;
- (id)gridCellImage;
- (id)getGenericIconImage:(int)arg1;
- (id)getUnmaskedIconImage:(int)arg1;
- (id)getIconImage:(int)arg1;
- (id)getStandardIconImageForLocation:(int)arg1;
- (BOOL)shouldCacheImageForFormat:(int)arg1;
- (id)generateIconImage:(int)arg1;
- (BOOL)launchEnabled;
- (id)tags;
- (BOOL)matchesEntity:(id)arg1;
- (NSInteger)localizedCompareDisplayNames:(id)arg1;
- (BOOL)canEllipsizeLabel;
- (id)displayName;
- (void)localeChanged;
- (void)dealloc;
- (id)init;
- (int)iconFormatForLocation:(int)arg1;
@property(readonly, nonatomic) BOOL shouldWarmUp;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(NSUInteger)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (BOOL)hasObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)description;

@end

@interface SBIcon (iOS8_4)

- (id)displayNameForLocation:(int)arg1;

@end
