//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "SBIconIndexNode-Protocol.h"

@class NSHashTable, SBFolder, SBIconIndexMutableList, SBIcon;

@interface SBIconListModel : NSObject <SBIconIndexNode, NSFastEnumeration>
{
    SBIconIndexMutableList *_icons;
    NSUInteger _maxIconCount;
    NSHashTable *_nodeObservers;
    NSHashTable *_listObservers;
    BOOL _iconStateIsDirty;
    SBFolder *_folder;
}

- (void)list:(id)arg1 didRemoveContainedNodeIdentifiers:(id)arg2;
- (void)list:(id)arg1 didAddContainedNodeIdentifiers:(id)arg2;
- (id)nodeDescriptionWithPrefix:(id)arg1;
- (void)removeNodeObserver:(id)arg1;
- (void)addNodeObserver:(id)arg1;
- (id)nodesAlongIndexPath:(id)arg1 consumedIndexes:(NSUInteger)arg2;
- (id)indexPathsForContainedNodeIdentifier:(id)arg1 prefixPath:(id)arg2;
- (id)containedNodeIdentifiers;
- (BOOL)containsNodeIdentifier:(id)arg1;
- (id)nodeIdentifier;
- (void)_notifyListObservers:(/*CDUnknownBlockType*/void*)arg1;
- (void)removeListObserver:(id)arg1;
- (void)addListObserver:(id)arg1;
- (void)warmUpIconImagesForLocation:(int)arg1;
- (id)description;
- (void)markIconStateClean;
- (BOOL)isIconStateDirty;
- (id)iconsOfClass:(Class)arg1;
- (NSUInteger)compactIcons;
- (BOOL)needsCompacting;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (NSUInteger)firstFreeSlotIndexForType:(int)arg1;
- (NSUInteger)firstFreeSlotIndex;
- (void)removeIcon:(id)arg1;
- (void)removeIconAtIndex:(NSUInteger)arg1;
- (id)insertIcon:(id)arg1 atIndex:(NSUInteger *)arg2;
- (id)placeIcon:(id)arg1 atIndex:(NSUInteger *)arg2;
- (BOOL)addIcon:(id)arg1 asDirty:(BOOL)arg2;
- (BOOL)addIcon:(id)arg1;
- (BOOL)allowsAddingIcon:(id)arg1;
- (BOOL)containsLeafIconWithIdentifier:(id)arg1;
- (BOOL)containsIcon:(id)arg1;
- (NSUInteger)indexForLeafIconWithIdentifier:(id)arg1;
- (NSUInteger)indexForIcon:(id)arg1;
- (id)iconAtIndex:(NSUInteger)arg1;
- (id)icons;
- (NSUInteger)maxNumberOfIcons;
- (NSUInteger)numberOfIcons;
- (id)folder;
- (void)dealloc;
- (id)init;
- (id)initWithFolder:(id)arg1 maxIconCount:(NSUInteger)arg2;

@end

