//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBReusableView-Protocol.h"

@class NSArray, SBIcon;

@protocol SBIconAccessoryView <SBReusableView>
+ (NSArray *)checkoutAccessoryImagesForIcon:(SBIcon *)arg1 location:(int)arg2;
- (void)setAccessoryBrightness:(double)arg1;
- (BOOL)displayingAccessory;
- (struct CGPoint)accessoryOriginForIconBounds:(struct CGRect)arg1;
- (void)configureForIcon:(SBIcon *)arg1 location:(int)arg2 highlighted:(BOOL)arg3;
- (void)configureAnimatedForIcon:(SBIcon *)arg1 location:(int)arg2 highlighted:(BOOL)arg3 withPreparation:(void (^)(void))arg4 animation:(void (^)(void))arg5 completion:(void (^)(BOOL))arg6;
@end

