//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import "CDStructures.h"
#import "SBIconListLayoutDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSMutableSet, SBIcon, SBIconListModel, SBIconViewMap;

@interface SBIconListView : UIView
{
    SBIconListModel *_model;
    SBIconViewMap *_viewMap;
    NSInteger _orientation;
    CGFloat _statusBarHeight;
    SBIcon *_bouncedIcon;
    NSMutableArray *_removedIcons;
    NSArray *_rotationContainers;
    unsigned int _needsLayout:1;
    unsigned int _rotating:1;
    UIView *_fadeView;
    BOOL _purged;
    NSMutableSet *_notShownIconViews;
    BOOL _isEditing;
    id <SBIconListLayoutDelegate> _layoutDelegate;
    struct CGRect _wallpaperRelativeFrame;
}

+ (NSUInteger)maxVisibleIcons;
+ (NSUInteger)maxIcons;
+ (NSUInteger)iconColumnsForInterfaceOrientation:(NSInteger)arg1;
+ (NSUInteger)maxVisibleIconRowsInterfaceOrientation:(NSInteger)arg1;
+ (NSUInteger)iconRowsForInterfaceOrientation:(NSInteger)arg1;
+ (NSInteger)rotationAnchor;
@property(nonatomic, assign) id <SBIconListLayoutDelegate> layoutDelegate; // @synthesize layoutDelegate=_layoutDelegate;
@property(nonatomic) struct CGRect wallpaperRelativeFrame; // @synthesize wallpaperRelativeFrame=_wallpaperRelativeFrame;
@property(nonatomic) CGFloat statusBarHeight; // @synthesize statusBarHeight=_statusBarHeight;
@property(nonatomic) NSInteger orientation; // @synthesize orientation=_orientation;
@property(nonatomic) BOOL purged; // @synthesize purged=_purged;
@property(nonatomic, getter=isEditing) BOOL editing; // @synthesize editing=_isEditing;
- (void)_sendLayoutDelegateLayoutInvalidated;
- (void)_sendLayoutDelegateWouldHaveMovedIcon:(id)arg1;
- (void)cleanupAfterRotation;
- (void)performRotationWithDuration:(double)arg1;
- (void)prepareToRotateToInterfaceOrientation:(NSInteger)arg1;
- (NSUInteger)rowAtPoint:(struct CGPoint)arg1;
- (NSUInteger)columnAtPoint:(struct CGPoint)arg1;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (CGFloat)verticalIconPadding;
- (CGFloat)horizontalIconPadding;
- (CGFloat)horizontalBumpForColumn:(NSUInteger)arg1;
- (CGFloat)sideIconInset;
- (CGFloat)bottomIconInset;
- (CGFloat)topIconInset;
- (id)bouncedIcon;
- (void)setBouncedIcon:(id)arg1;
- (BOOL)isDock;
- (void)_updateEditingStateForIcons:(id)arg1 animated:(BOOL)arg2;
- (void)updateEditingStateAnimated:(BOOL)arg1;
- (void)showIconImagesFromColumn:(NSInteger)arg1 toColumn:(NSInteger)arg2 totalColumns:(NSInteger)arg3 allowAnimations:(BOOL)arg4;
- (void)showAllIcons;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(NSUInteger *)arg2 proposedOrder:(int *)arg3 grabbedIcon:(id)arg4;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(NSUInteger *)arg2;
- (void)layoutIconsIfNeeded:(double)arg1 domino:(BOOL)arg2;
- (void)layoutIconsNow;
- (void)setIconsNeedLayout;
- (void)setFrame:(struct CGRect)arg1;
- (NSUInteger)indexOfIcon:(id)arg1;
- (struct SBIconCoordinate)coordinateForIconAtIndex:(NSUInteger)arg1;
- (struct SBIconCoordinate)coordinateForIcon:(id)arg1;
- (id)viewForIcon:(id)arg1;
- (struct CGPoint)centerForIconCoordinate:(struct SBIconCoordinate)arg1;
- (struct CGPoint)centerForIcon:(id)arg1;
- (struct CGPoint)originForIcon:(id)arg1;
- (struct CGPoint)originForIconAtIndex:(NSUInteger)arg1;
- (struct CGSize)defaultIconSize;
- (void)removeAllIconAnimations;
- (void)setAlphaForAllIcons:(double)arg1;
- (void)removeIcon:(id)arg1;
- (void)removeIconAtIndex:(NSUInteger)arg1;
- (id)removedIcons;
- (id)insertIcon:(id)arg1 atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3;
- (id)insertIcon:(id)arg1 atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (id)placeIcon:(id)arg1 atIndex:(NSUInteger)arg2 moveNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_layoutIcon:(id)arg1 atIndex:(NSUInteger)arg2 createViewNow:(BOOL)arg3 pop:(BOOL)arg4;
- (void)_popIconView:(id)arg1;
- (NSUInteger)firstFreeSlotOrLastSlotIndexForType:(int)arg1;
- (NSUInteger)firstFreeSlotOrLastSlotIndex;
- (NSUInteger)firstFreeSlotIndexForType:(int)arg1;
- (NSUInteger)firstFreeSlotIndex;
- (BOOL)containsIcon:(id)arg1;
- (BOOL)isFull;
- (BOOL)isEmpty;
- (id)visibleIcons;
- (id)icons;
- (BOOL)compactIcons:(BOOL)arg1;
- (NSUInteger)rowForIcon:(id)arg1;
- (id)description;
- (struct SBIconCoordinate)iconCoordinateForIndex:(NSUInteger)arg1 forOrientation:(NSInteger)arg2;
- (NSUInteger)indexForCoordinate:(struct SBIconCoordinate)arg1 forOrientation:(NSInteger)arg2;
- (int)iconLocation;
- (NSUInteger)iconRowsForSpacingCalculation;
- (NSUInteger)iconsInRowForSpacingCalculation;
- (NSUInteger)iconColumnsForCurrentOrientation;
- (NSUInteger)iconRowsForCurrentOrientation;
- (struct CGPoint)_wallpaperRelativeIconCenterForIconView:(id)arg1;
- (struct CGPoint)_wallpaperRelativeIconCenterForIconImageCenter:(struct CGPoint)arg1;
- (Class)baseIconViewClass;
- (id)viewMap;
- (SBIconListModel*)model;
- (void)setModel:(SBIconListModel*)arg1;
- (id)tintColor;
- (void)dealloc;
- (id)initWithModel:(SBIconListModel*)arg1 orientation:(NSInteger)arg2 viewMap:(id)arg3;
- (id)init;
- (Class)modelClass;

@end
