//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "SBIconObserver-Protocol.h"
#import "SBReusableView-Protocol.h"
#import "SBIconAccessoryView-Protocol.h"
#import "SBIconViewDelegate-Protocol.h"
#import "SBIconViewObserver-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSTimer, SBCloseBoxView, SBFParallaxSettings, SBFolderIconBackgroundView, SBIcon, SBIconImageCrossfadeView, SBIconImageView, SBIconLabelView, _UILegibilitySettings;

@interface SBIconView : UIView <_UISettingsKeyObserver, SBIconObserver, SBReusableView>
{
    SBIcon *_icon;
    int _iconLocation;
    UIView *_currentImageView;
    SBIconImageView *_iconImageView;
    SBIconImageCrossfadeView *_crossfadeView;
    UIView<SBIconAccessoryView> *_accessoryView;
    SBCloseBoxView *_closeBox;
    SBFParallaxSettings *_closeBoxParallaxSettings;
    struct CGPoint _wallpaperRelativeCloseBoxCenter;
    SBIconLabelView *_labelView;
    UIView *_updatedMark;
    SBFolderIconBackgroundView *_dropGlow;
    unsigned int _drawsLabel:1;
    unsigned int _isEditing:1;
    unsigned int _isPaused:1;
    unsigned int _isGrabbed:1;
    unsigned int _isOverlapping:1;
    unsigned int _refusesRecipientStatus:1;
    unsigned int _highlighted:1;
    unsigned int _launchDisabled:1;
    unsigned int _isJittering:1;
    unsigned int _allowJitter:1;
    unsigned int _touchDownInIcon:1;
    unsigned int _hideLabel:1;
    unsigned int _hideUpdatedMark;
    struct CGPoint _unjitterPoint;
    struct CGPoint _grabPoint;
    NSTimer *_longPressTimer;
    struct CGRect _visibleImageRect;
    id <SBIconViewDelegate> _delegate;
    id <SBIconViewObserver> _observer;
    _UILegibilitySettings *_legibilitySettings;
    CGFloat _iconImageAlpha;
    CGFloat _iconAccessoryAlpha;
    CGFloat _iconLabelAlpha;
    struct CGPoint _wallpaperRelativeImageCenter;
}

+ (id)_jitterTransformAnimation;
+ (id)_jitterPositionAnimation;
+ (struct CGSize)maxLabelSize;
+ (struct CGRect)_rectForLayoutMetric:(int)arg1;
+ (struct CGSize)defaultVisibleIconImageSize;
+ (struct CGPoint)defaultIconImageCenter;
+ (struct CGSize)defaultIconImageSize;
+ (CGFloat)_labelHeight;
+ (CGSize)defaultIconSize;
+ (CGFloat)updatedMarkRightMargin;
+ (BOOL)canShowUpdatedMark;
+ (int)_defaultIconFormat;
@property(nonatomic) struct CGPoint wallpaperRelativeImageCenter; // @synthesize wallpaperRelativeImageCenter=_wallpaperRelativeImageCenter;
@property(nonatomic) CGFloat iconLabelAlpha; // @synthesize iconLabelAlpha=_iconLabelAlpha;
@property(nonatomic) CGFloat iconAccessoryAlpha; // @synthesize iconAccessoryAlpha=_iconAccessoryAlpha;
@property(nonatomic) CGFloat iconImageAlpha; // @synthesize iconImageAlpha=_iconImageAlpha;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) int location; // @synthesize location=_iconLocation;
@property(nonatomic, assign) id <SBIconViewObserver> observer; // @synthesize observer=_observer;
@property(nonatomic, assign) id <SBIconViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)iconLaunchEnabledDidChange:(id)arg1;
- (void)iconAccessoriesDidUpdate:(id)arg1;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_backgroundContrastDidChange:(id)arg1;
- (void)_updateProgressAnimated:(BOOL)arg1;
- (void)prepareForReuse;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (BOOL)_delegateTapAllowed;
- (void)_delegateTouchEnded:(BOOL)arg1;
- (struct UIEdgeInsets)snapshotEdgeInsets;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_closeBoxTapped;
- (BOOL)_isShowingCloseBox;
- (void)_updateCloseBoxAnimated:(BOOL)arg1;
- (void)_applyEditingStateAnimated:(BOOL)arg1;
@property(nonatomic) BOOL isEditing;
- (void)setIsEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setTouchDownInIcon:(BOOL)arg1;
- (BOOL)isTouchDownInIcon;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)didMoveToWindow;
- (void)cancelLongPressTimer;
- (void)longPressTimerFired;
- (void)cleanupAfterImageCrossfade;
- (void)setImageCrossfadeMorphFraction:(double)arg1 totalScale:(double)arg2;
- (void)setImageCrossfadeFadeFraction:(double)arg1;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3 anchorPoint:(struct CGPoint)arg4;
- (void)prepareToCrossfadeImageWithView:(id)arg1 maskCorners:(BOOL)arg2 trueCrossfade:(BOOL)arg3;
- (id)dropGlow;
- (void)removeDropGlow;
- (void)showDropGlow:(BOOL)arg1;
- (void)prepareDropGlow;
- (void)setIsOverlapping:(BOOL)arg1;
- (BOOL)isGrabbed;
- (void)setIsGrabbed:(BOOL)arg1;
- (double)grabDurationForEvent:(id)arg1;
- (BOOL)canReceiveGrabbedIcon:(id)arg1;
- (void)setRefusesRecipientStatus:(BOOL)arg1;
- (void)setIconPosition:(struct CGPoint)arg1;
- (void)removeAllIconAnimations;
- (void)setAllowJitter:(BOOL)arg1;
- (void)_updateJitter;
- (void)_recursivelyUpdateBackdropMaskFrames;
- (void)_recursiveNotifyInteractionTintColorDidChangeForReasons:(NSUInteger)arg1;
- (id)tintColor;
- (void)setFrame:(struct CGRect)arg1;
- (BOOL)isInDock;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)isHighlighted;
- (BOOL)allowsTapWhileEditing;
- (void)_updateBrightness;
- (BOOL)pointMostlyInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)_automationID;
- (void)_createAccessoryViewIfNecessary;
- (void)_updateAccessoryViewWithAnimation:(BOOL)arg1;
- (void)_updateIconImageViewAnimated:(BOOL)arg1;
- (void)_updateUpdatedMark;
- (id)_legibilitySettingsWithStyle:(NSInteger)arg1 primaryColor:(id)arg2;
- (id)_legibilitySettingsWithPrimaryColor:(id)arg1;
- (id)_legibilitySettingsWithParameters:(id)arg1;
- (void)_updateLabel;
- (id)_labelImageParameters;
- (void)invalidateLabelLayoutGeometry;
- (void)_updateAdaptiveColors;
- (void)setShouldRasterizeImageView:(BOOL)arg1;
- (void)setSuppressesBlurryBackgroundChanges:(BOOL)arg1;
- (id)_labelImage;
- (id)_iconImageView;
- (struct CGPoint)_centerForCloseBoxRelativeToVisibleImageFrame:(struct CGRect)arg1;
- (struct CGPoint)_centerForCloseBox;
- (struct CGRect)_frameForAccessoryView;
- (struct CGRect)_frameForUpdatedMarkWithLabelFrame:(struct CGRect)arg1;
- (struct CGRect)_frameForLabel;
- (struct CGRect)_frameForVisibleImage;
- (double)_labelVerticalOffset;
- (struct CGRect)_frameForImageView;
- (void)layoutSubviews;
- (void)setUpdatedMarkHidden:(BOOL)arg1;
- (void)setLabelHidden:(BOOL)arg1;
- (void)_applyIconLabelAlpha:(double)arg1;
- (void)_applyIconAccessoryAlpha:(double)arg1;
- (void)_applyIconImageAlpha:(double)arg1;
- (void)setIconImageAndAccessoryAlpha:(double)arg1;
- (struct CGSize)iconImageVisibleSize;
- (struct CGPoint)iconImageCenter;
- (struct CGRect)iconImageFrame;
- (id)iconImageSnapshot;
- (void)swapInIcon:(id)arg1;
@property(retain, nonatomic) SBIcon *icon;
- (void)_setIcon:(id)arg1 animated:(BOOL)arg2;
- (void)setPaused:(BOOL)arg1;
- (void)dealloc;
- (id)initWithDefaultSize;

@end

