//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconZoomAnimator.h"
#import "CDStructures.h"

@class SBIcon, SBIconView, SBScaleZoomSettings, UIView;

@interface SBScaleIconZoomAnimator : SBIconZoomAnimator
{
    struct UIEdgeInsets _iconScootch;
    CGFloat _dockStretch;
    struct SBIconCoordinate _dockListCenterCoordinate;
    struct SBIconCoordinate _mainListCenterCoordinate;
    CGFloat _naturalVisualAltitude;
    UIView *_scalingView;
    SBIcon *_targetIcon;
    CGFloat _zoomScale;
}

@property(readonly, nonatomic) CGFloat zoomScale; // @synthesize zoomScale=_zoomScale;
@property(readonly, nonatomic) SBIcon *targetIcon; // @synthesize targetIcon=_targetIcon;
- (void)_calculateIconScootch;
- (struct CGPoint)_scootchForIcon:(id)arg1 inDock:(BOOL)arg2;
- (void)_applyOuterFadeFraction:(CGFloat)arg1;
- (void)_applyZoomFraction:(CGFloat)arg1;
- (CGFloat)_zoomedVisualAltitude;
- (struct CGPoint)_zoomedIconCenter;
- (struct CGRect)_zoomedFrame;
- (void)_animateToFraction:(CGFloat)arg1 afterDelay:(CGFloat)arg2 withSharedCompletion:(void*)arg3;
- (NSUInteger)_numberOfSignificantAnimations;
- (void)_cleanupAnimation;
- (void)_setAnimationFraction:(CGFloat)arg1;
- (void)_prepareAnimation;
@property(readonly, nonatomic) SBIconView *targetIconView;
- (void)dealloc;
- (id)initWithFolderController:(id)arg1 targetIcon:(id)arg2;

// Remaining properties
//@property(retain, nonatomic) SBScaleZoomSettings *settings;

@end

