//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDStructures.h"

@class UIColor, UIImage, UIImageView;

@interface SBWallpaperEffectView : UIView
{
    NSInteger _variant;
    UIColor *_wallpaperAverageColor;
    NSInteger _startStyle;
    NSInteger _endStyle;
    double _transitionFraction;
    UIView *_blurView;
    UIView *_grayscaleTintView;
    UIView *_colorTintView;
    UIView *_transitionBlurView;
    UIView *_transitionGrayscaleTintView;
    UIView *_transitionColorTintView;
    UIImageView *_maskImageView;
    UIView *_blurMaskingContainer;
    UIView *_tintMaskingContainer;
    UIImage *_maskImage;
    BOOL _shouldMaskBlur;
    BOOL _shouldMaskTint;
    BOOL _accessibilityIncreaseContrastEnabled;
}

+ (id)imageInRect:(struct CGRect)arg1 forVariant:(NSInteger)arg2 withStyle:(NSInteger)arg3 zoomFactor:(double)arg4 mask:(id)arg5 masksBlur:(BOOL)arg6 masksTint:(BOOL)arg7;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_accessibilityEnhanceBackgroundContrastChanged:(id)arg1;
- (void)_clearView:(id *)arg1;
- (void)_configureGrayscaleTintView:(id *)arg1 colorTintView:(id *)arg2 forStyle:(NSInteger)arg3;
- (void)_configureViews;
- (void)_configureForCurrentBlurStyle;
- (void)_configureFromScratch;
- (void)_setTransitionFraction:(double)arg1;
- (void)_updateWallpaperAverageColor:(id)arg1;
- (void)wallpaperDidChangeForVariant:(NSInteger)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(NSInteger)arg2;
- (void)fakeBlurView:(id)arg1 didChangeStyle:(NSInteger)arg2;
- (void)layoutSubviews;
- (void)setMaskImage:(id)arg1 masksBlur:(BOOL)arg2 masksTint:(BOOL)arg3;
- (BOOL)currentTransitionStateIsOpaque;
- (void)setTransitionState:(CDStruct_059c2b36)arg1;
- (BOOL)prepareToAnimateToTransitionState:(inout CDStruct_059c2b36 *)arg1;
- (void)setStyle:(NSInteger)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithWallpaperVariant:(NSInteger)arg1;

@end

