/*
* This header is generated by classdump-dyld 0.7
* on Wednesday, July 22, 2015 at 7:09:58 PM Japan Standard Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/

#import <Music/Music-Structs.h>
#import <UIKit/UIResponder.h>
#import <UIKit/UIApplicationTestingDelegate.h>
#import <Music/MusicRadioApplicationDelegate.h>
#import <Music/MusicRemoteControllerDelegate.h>
#import <Music/MusicTransferObserver.h>
#import <Music/MusicWelcomeNavigationControllerDisappearanceObserver.h>
#import <Music/SKUIApplicationDelegate.h>
#import <Music/SKUIApplicationUpdatableAssetsDelegate.h>
#import <Music/SKUIStatusOverlayProvider.h>
#import <Music/MusicApplicationDelegate.h>
@class MusicRemoteController;


@protocol MusicApplicationDelegate <UIApplicationDelegate>
@property (nonatomic,readonly) MusicRemoteController * remoteController; 
@required
-(MusicRemoteController *)remoteController;

@end


@class MusicRemoteController, MPAVItem, MPUJinglePlayActivityReportingController, MusicPlayerServerDelegate, MPUserNotification, RadioRecentStationsController, MPRemoteRadioController, MPUReportingPlaybackObserver, UIAlertController, MusicTransferAggregator, MusicWelcomeNavigationController, MusicWelcomePlaceholderView, MusicApplicationController, UIWindow, NSString;

@interface MusicApplicationDelegate : UIResponder <UIApplicationTestingDelegate, MusicRadioApplicationDelegate, MusicRemoteControllerDelegate, MusicTransferObserver, MusicWelcomeNavigationControllerDisappearanceObserver, SKUIApplicationDelegate, SKUIApplicationUpdatableAssetsDelegate, SKUIStatusOverlayProvider, MusicApplicationDelegate> {

	char _allowsNewPlaybackErrorItem;
	MPAVItem* _allowedPlaybackErrorItem;
	MPUJinglePlayActivityReportingController* _jinglePlayActivityReportingController;
	int _networkStartCount;
	char _onActiveShouldResumeApplication;
	MusicPlayerServerDelegate* _musicPlayerServerDelegate;
	MPUserNotification* _playbackErrorUserNotification;
	RadioRecentStationsController* _recentStationsController;
	MusicRemoteController* _remoteController;
	MPRemoteRadioController* _remoteRadioController;
	MPUReportingPlaybackObserver* _reportingPlaybackObserver;
	UIAlertController* _subscriptionLeasePauseAlertController;
	unsigned long long _subscriptionLeasePauseRevisionID;
	int _tabState;
	MusicTransferAggregator* _transferAggregator;
	MusicWelcomeNavigationController* _welcomeNavigationController;
	MusicWelcomePlaceholderView* _welcomePlaceholderView;
	MusicApplicationController* _applicationController;
	UIWindow* _window;

}

@property (readonly) unsigned hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) UIWindow * window; 
@property (nonatomic,readonly) MusicApplicationController * applicationController;              //@synthesize applicationController=_applicationController - In the implementation block
@property (nonatomic,retain) UIWindow * window;                                                 //@synthesize window=_window - In the implementation block
@property (nonatomic,readonly) MusicRemoteController * remoteController; 
-(void)_supportedTabIdentifiersDidChangeNotification:(id)arg1 ;
-(void)_cloudServiceControllerSubscriptionStatusDidChangeNotification:(id)arg1 ;
-(void)_cloudServiceControllerCloudLibraryEnabledDidChangeNotification:(id)arg1 ;
-(void)_configureRadioOperationQueue;
-(void)_networkingStartNotification:(id)arg1 ;
-(void)_networkingStopNotification:(id)arg1 ;
-(void)_playerPlaybackLeaseControllerDidPausePlaybackForLeaseEndNotification:(id)arg1 ;
-(void)_playerPlaybackErrorNotification:(id)arg1 ;
-(void)_updateTabBarItemsAnimated:(char)arg1 ;
-(id)_fairPlaySAPSession;
-(void)radioApplicationWillFinishLaunching:(id)arg1 ;
-(char)_isOfflineForReporting;
-(unsigned long long)_storeAccountIdentifierForReporting;
-(void)_setIAmTheIPod;
-(void)_setupWindowIfNecessary;
-(void)_presentWelcomeScreenIfAppropriate;
-(id)_validatedUserActivityContextWithContext:(id)arg1 ;
-(char)_handleUserActivityContext:(id)arg1 ;
-(void)radioApplicationDidFinishLaunching:(id)arg1 ;
-(void)_populateMediaSocialProfileCache;
-(void)_presentNowPlayingViewControllerForSharing;
-(void)presentNowPlayingViewControllerAnimated:(char)arg1 ;
-(void)_populateMediaSocialAdminPermissionsCache;
-(void)_disableAllowsNewPlaybackErrorItemIfAppropriate;
-(char)_hasTabWithIdentifier:(id)arg1 ;
-(void)_switchViewTest:(id)arg1 fromIdentifier:(id)arg2 toIdentifier:(id)arg3 ;
-(void)_scrollViewTest:(id)arg1 withOptions:(id)arg2 withIdentifier:(id)arg3 ;
-(void)_bringUpActionSheet:(id)arg1 ;
-(void)_enterRecentlyAdded:(id)arg1 ;
-(void)_switchToLibraryDetailView:(id)arg1 ;
-(void)_switchToViewConfigurationTest:(id)arg1 ;
-(void)_dismissNowPlayingViewControllerAnimated:(char)arg1 ;
-(void)_switchToMyMusicTabAndSegmentWithIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_switchToTabWithIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_playLocalLibrarySongForTestNamed:(id)arg1 ;
-(void)_searchLocalLibraryForTestName:(id)arg1 withOptions:(id)arg2 ;
-(void)_selectViewConfigurationWithIdentifier:(id)arg1 inLibrarySplitViewController:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)_selectFirstItemFromLibraryBrowseTableViewController:(id)arg1 ;
-(void)_switchToDetailSegmentedTabView:(id)arg1 withIdentifier:(id)arg2 ;
-(void)_switchToViewConfiguration:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_switchToSegmentedTabWithIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)remoteController:(id)arg1 addStationWithDictionary:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)remoteController:(id)arg1 completeAdditionOfStationWithContext:(id)arg2 animated:(char)arg3 ;
-(void)_showAddSharedStationFailedAlertWithErrorCode:(int)arg1 ;
-(void)_itemDidChangeNotification:(id)arg1 ;
-(void)_playerWillReloadWithPlaybackContextNotification:(id)arg1 ;
-(void)_networkTypeDidChangeNotification:(id)arg1 ;
-(void)dealloc;
-(UIWindow *)window;
-(id)init;
-(char)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(char)application:(id)arg1 shouldSaveApplicationState:(id)arg2 ;
-(char)application:(id)arg1 shouldRestoreApplicationState:(id)arg2 ;
-(char)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(char)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)setWindow:(UIWindow *)arg1 ;
-(char)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(/*^block*/id)arg3 ;
-(char)application:(id)arg1 willContinueUserActivityWithType:(id)arg2 ;
-(void)application:(id)arg1 willEncodeRestorableStateWithCoder:(id)arg2 ;
-(void)application:(id)arg1 didDecodeRestorableStateWithCoder:(id)arg2 ;
-(char)application:(id)arg1 runTest:(id)arg2 options:(id)arg3 ;
-(void)_playerDidReloadWithPlaybackContextNotification:(id)arg1 ;
-(void)transferAggregatorDidChange:(id)arg1 ;
-(MusicRemoteController *)remoteController;
-(void)welcomeNavigationControllerDidDisappear:(id)arg1 ;
-(void)_itemWillChangeNotification:(id)arg1 ;
-(MusicApplicationController *)applicationController;
-(void)_availableMediaLibrariesDidChangeNotification:(id)arg1 ;
-(void)_isExplicitTracksEnabledDidChangeNotification:(id)arg1 ;
-(id)overlayViewControllerWithBackgroundStyle:(int)arg1 ;
-(char)shouldShowStatusOverlayForViewController:(id)arg1 ;
-(void)application:(id)arg1 evaluateAppJavaScriptInContext:(id)arg2 JSContext:(id)arg3 ;
-(void)application:(id)arg1 didSelectTabBarItem:(id)arg2 ;
-(void)applicationDidLoadFromUpdatableAssetsCache:(id)arg1 ;
-(id)bundledUpdatableAssetsManifestURL;
-(char)clearUpdatableAssetsCacheOnLaunch;
-(char)loadApplicationAfterUpdatableAssetsRefresh;
-(id)updatableAssetsManifestURL;
-(id)application:(id)arg1 navigationControllerWithTabBarItem:(id)arg2 ;
-(void)applicationDidChangeClientContext:(id)arg1 ;
-(void)_accountStoreDidChangeNotification:(id)arg1 ;
@end

@interface AFConnectionClientServiceDelegate : NSObject <AFClientServiceDelegate> {
    AFConnection *_connection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_connectionDelegate;
- (void)aceConnectionWillRetryOnError:(id)arg1;
- (void)acousticIDRequestDidFinishWithSuccess:(BOOL)arg1;
- (void)acousticIDRequestWillStart;
- (void)getBulletinContext:(id /* block */)arg1;
- (id)initWithConnection:(id)arg1;
- (void)invalidateCurrentUserActivity;
- (void)musicWasDetected;
- (void)requestDidFailWithError:(id)arg1 requestClass:(id)arg2;
- (void)requestDidFinish;
- (void)requestDidReceiveCommand:(id)arg1 reply:(id /* block */)arg2;
- (void)requestRequestedDismissAssistant;
- (void)requestRequestedOpenApplicationWithBundleID:(id)arg1 URL:(id)arg2 reply:(id /* block */)arg3;
- (void)requestRequestedOpenURL:(id)arg1 reply:(id /* block */)arg2;
- (void)setUserActivityInfo:(id)arg1 webpageURL:(id)arg2;
- (void)shouldSpeakChanged:(BOOL)arg1;
- (void)speechRecognitionDidFail:(id)arg1;
- (void)speechRecognized:(id)arg1;
- (void)speechRecognizedPartialResult:(id)arg1;
- (void)speechRecordingDidBeginOnAVRecordRoute:(id)arg1;
- (void)speechRecordingDidCancel;
- (void)speechRecordingDidChangeAVRecordRoute:(id)arg1;
- (void)speechRecordingDidEnd;
- (void)speechRecordingDidFail:(id)arg1;
- (void)speechRecordingWillBeginWithLevelsSharedMem:(id)arg1;

@end

@interface AFSiriTask : NSObject <BSXPCCoding, NSSecureCoding> {
    NSXPCListenerEndpoint *_remoteResponseListenerEndpoint;
    AFSiriRequest *_request;
    NSXPCListenerEndpoint *_usageResultListenerEndpoint;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;

+ (void)initialize;
+ (BOOL)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_initWithRequest:(id)arg1 remoteResponseListenerEndpoint:(id)arg2 usageResultListenerEndpoint:(id)arg3;
- (id)_responseHandlerConnection;
- (id)_usageResultHandlerConnection;
- (void)completeWithResponse:(id)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithXPCDictionary:(id)arg1;
- (void)failWithError:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithXPCDictionary:(id)arg1;
- (void)reportUsageResult:(id)arg1;
- (id)request;

@end

@interface AFUIApplicationSiriTaskDeliverer : NSObject <AFSiriTaskDelivering> {
    NSString *_appBundleIdentifier;
    BKSApplicationStateMonitor *_appStateMonitor;
    AFWatchdogTimer *_assertionTimer;
    BKSProcessAssertion *_bKSAssertionForBgLaunch;
    NSObject<OS_dispatch_group> *_group;
    NSObject<OS_dispatch_queue> *_queue;
    AFSiriTaskmaster *_taskmaster;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned int hash;
@property (readonly) Class superclass;
@property (nonatomic) AFSiriTaskmaster *taskmaster;

- (void).cxx_destruct;
- (void)_invalidateAssertionTimer;
- (void)_invalidateBackboardServices;
- (id)_queue;
- (void)deliverSiriTask:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)description;
- (id)initWithAppBundleIdentifier:(id)arg1;
- (void)setTaskmaster:(id)arg1;
- (void)siriTaskDidFinish;
- (id)taskmaster;

@end

