/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:21 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@interface CCUIControlCenterSectionView : UIView {

	NSInteger _layoutStyle;

}

@property (assign,nonatomic) NSInteger layoutStyle;              //@synthesize layoutStyle=_layoutStyle - In the implementation block
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(NSInteger)layoutStyle;
-(void)setLayoutStyle:(NSInteger)arg1 ;
@end
