include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Messages
Messages_BUNDLE_NAME = com.creatix.messages
Messages_BUNDLE_EXTENSION = block
Messages_CFLAGS =  -fobjc-arc
Messages_FILES = $(wildcard *.m)
Messages_FRAMEWORKS = Foundation UIKit
Messages_INSTALL_PATH = /var/mobile/Library/Curago/Widgets/

include $(THEOS_MAKE_PATH)/bundle.mk
