/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:09 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MPUFoundation.framework/MPUFoundation
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@interface MPULayoutInterpolator : NSObject <NSCopying> {

	BOOL _hasEntryWithSpecificSecondaryReferenceMetric;

}
// -(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)addValue:(CGFloat)arg1 forReferenceMetric:(CGFloat)arg2 ;
-(void)addValue:(CGFloat)arg1 forReferenceMetric:(CGFloat)arg2 secondaryReferenceMetric:(CGFloat)arg3 ;
-(CGFloat)valueForReferenceMetric:(CGFloat)arg1 secondaryReferenceMetric:(CGFloat)arg2 ;
-(CGFloat)valueForReferenceMetric:(CGFloat)arg1 ;
@end
