GO_EASY_ON_ME = 1
SDKVERSION = 8.4
ARCHS = armv7 arm64
FINALPACKAGE = 1
MoreSiri_LDFLAGS += -Wl,-segalign,4000


include theos/makefiles/common.mk
TWEAK_NAME = MoreSiri
MoreSiri_FILES = Tweak.xm
#MoreSiri_LIBRARIES = inspectivec

include $(THEOS_MAKE_PATH)/tweak.mk
