#!/bin/sh
#cleaning old preferences
rm -rf /var/mobile/Library/Preferences/com.julioverne.cydiaenable.plist

declare -a cydia
cydia=($CYDIA)

if [[ ${CYDIA+@} ]]; then
            eval "echo 'finish:reopen' >&${cydia[0]}"
fi

exit 0