/*
* This header is generated by classdump-dyld 1.0
* on Thursday, December 22, 2016 at 6:07:04 PM Eastern European Standard Time
* Operating System: Version 10.1.1 (Build 14B100)
* Image Source: /System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

#import <BulletinBoard/BBContent.h>
#import <BulletinBoard/BBSectionIcon.h>
#import <BulletinBoard/BBAccessoryIcon.h>
#import <BulletinBoard/BBSound.h>
#import <BulletinBoard/BBAttachmentMetadata.h>
#import <BulletinBoard/BBColor.h>
#import <BulletinBoard/BBAction.h>

@class NSString, NSSet, NSArray, BBContent, BBSectionIcon, NSDate, NSTimeZone, BBAccessoryIcon, BBSound, BBAttachmentMetadata, NSMutableDictionary, NSDictionary, NSMutableArray, NSHashTable, BBColor, BBAction;

@interface BBBulletin : NSObject <NSCopying, NSSecureCoding> {

	BOOL _hasEventDate;
	BOOL _dateIsAllDay;
	BOOL _clearable;
	BOOL _turnsOnDisplay;
	BOOL _wantsFullscreenPresentation;
	BOOL _ignoresQuietMode;
	BOOL _expiresOnPublisherDeath;
	BOOL _hasPrivateContent;
	BOOL _usesExternalSync;
	BOOL _loading;
	NSString* _sectionID;
	NSSet* _subsectionIDs;
	NSString* _publisherRecordID;
	NSString* _publisherBulletinID;
	NSString* _dismissalID;
	NSString* _categoryID;
	NSString* _threadID;
	NSArray* _peopleIDs;
	NSInteger _addressBookRecordID;
	NSInteger _sectionSubtype;
	NSArray* _intentIDs;
	NSUInteger _counter;
	BBContent* _content;
	BBContent* _modalAlertContent;
	BBContent* _starkBannerContent;
	BBSectionIcon* _icon;
	NSDate* _date;
	NSDate* _endDate;
	NSDate* _recencyDate;
	NSInteger _dateFormatStyle;
	NSTimeZone* _timeZone;
	BBAccessoryIcon* _accessoryIconMask;
	BBSound* _sound;
	BBAttachmentMetadata* _primaryAttachment;
	NSArray* _additionalAttachments;
	NSString* _unlockActionLabelOverride;
	NSMutableDictionary* _actions;
	NSMutableDictionary* _supplementaryActionsByLayout;
	NSArray* _buttons;
	NSDictionary* _context;
	NSDate* _expirationDate;
	NSUInteger _expirationEvents;
	NSSet* _alertSuppressionContexts;
	NSString* _bulletinID;
	NSDate* _lastInterruptDate;
	NSDate* _publicationDate;
	NSString* _bulletinVersionID;
	NSMutableArray* _lifeAssertions;
	NSHashTable* _observers;
	NSString* _parentSectionID;
	NSString* _universalSectionID;
	NSUInteger realertCount_deprecated;
	NSSet* alertSuppressionAppIDs_deprecated;

}

@property (nonatomic,readonly) NSString * sectionDisplayName; 
@property (nonatomic,readonly) BBSectionIcon * sectionIcon; 
@property (nonatomic,readonly) BOOL sectionDisplaysCriticalBulletins; 
@property (nonatomic,readonly) BOOL showsSubtitle; 
@property (nonatomic,readonly) NSUInteger messageNumberOfLines; 
@property (nonatomic,readonly) BOOL usesVariableLayout; 
@property (nonatomic,readonly) BOOL orderSectionUsingRecencyDate; 
@property (nonatomic,readonly) BOOL showsDateInFloatingLockScreenAlert; 
@property (nonatomic,readonly) NSString * topic; 
@property (nonatomic,readonly) NSString * missedBannerDescriptionFormat; 
@property (nonatomic,readonly) NSString * fullUnlockActionLabel; 
@property (nonatomic,readonly) NSString * unlockActionLabel; 
@property (nonatomic,readonly) NSSet * alertSuppressionAppIDs; 
@property (nonatomic,readonly) BOOL suppressesAlertsWhenAppIsActive; 
@property (nonatomic,readonly) BOOL coalescesWhenLocked; 
@property (nonatomic,readonly) BOOL suppressesMessageForPrivacy; 
@property (nonatomic,readonly) NSUInteger realertCount; 
@property (nonatomic,readonly) BOOL inertWhenLocked; 
@property (nonatomic,readonly) BOOL preservesUnlockActionCase; 
@property (nonatomic,readonly) BOOL visuallyIndicatesWhenDateIsInFuture; 
@property (nonatomic,readonly) NSString * fullAlternateActionLabel; 
@property (nonatomic,readonly) NSString * alternateActionLabel; 
@property (nonatomic,readonly) BOOL canBeSilencedByMenuButtonPress; 
@property (nonatomic,readonly) BOOL preventLock; 
@property (nonatomic,readonly) BOOL suppressesTitle; 
@property (nonatomic,readonly) BOOL showsUnreadIndicatorForNoticesFeed; 
@property (nonatomic,readonly) BOOL showsContactPhoto; 
@property (nonatomic,readonly) BOOL playsSoundForModify; 
@property (nonatomic,readonly) BOOL allowsAutomaticRemovalFromLockScreen; 
@property (nonatomic,readonly) BOOL allowsAddingToLockScreenWhenUnlocked; 
@property (nonatomic,readonly) BOOL prioritizeAtTopOfLockScreen; 
@property (nonatomic,readonly) BOOL preemptsPresentedAlert; 
@property (nonatomic,readonly) BOOL revealsAdditionalContentOnPresentation; 
@property (nonatomic,readonly) NSUInteger subtypePriority; 
@property (nonatomic,readonly) NSInteger iPodOutAlertType; 
@property (nonatomic,readonly) BBColor * tintColor; 
@property (nonatomic,readonly) NSString * bannerAccessoryRemoteViewControllerClassName; 
@property (nonatomic,readonly) NSString * bannerAccessoryRemoteServiceBundleIdentifier; 
@property (nonatomic,readonly) NSString * secondaryContentRemoteViewControllerClassName; 
@property (nonatomic,readonly) NSString * secondaryContentRemoteServiceBundleIdentifier; 
@property (nonatomic,readonly) NSUInteger privacySettings; 
@property (nonatomic,copy) NSString * section; 
@property (nonatomic,copy) NSString * sectionID;                                                      //@synthesize sectionID=_sectionID - In the implementation block
@property (nonatomic,copy) NSSet * subsectionIDs;                                                     //@synthesize subsectionIDs=_subsectionIDs - In the implementation block
@property (nonatomic,copy) NSString * recordID;                                                       //@synthesize publisherRecordID=_publisherRecordID - In the implementation block
@property (nonatomic,copy) NSString * publisherBulletinID;                                            //@synthesize publisherBulletinID=_publisherBulletinID - In the implementation block
@property (nonatomic,copy) NSString * dismissalID;                                                    //@synthesize dismissalID=_dismissalID - In the implementation block
@property (nonatomic,copy) NSString * categoryID;                                                     //@synthesize categoryID=_categoryID - In the implementation block
@property (nonatomic,copy) NSString * threadID;                                                       //@synthesize threadID=_threadID - In the implementation block
@property (nonatomic,copy) NSArray * peopleIDs;                                                       //@synthesize peopleIDs=_peopleIDs - In the implementation block
@property (assign,nonatomic) NSInteger addressBookRecordID;                                           //@synthesize addressBookRecordID=_addressBookRecordID - In the implementation block
@property (assign,nonatomic) NSInteger sectionSubtype;                                                //@synthesize sectionSubtype=_sectionSubtype - In the implementation block
@property (nonatomic,copy) NSArray * intentIDs;                                                       //@synthesize intentIDs=_intentIDs - In the implementation block
@property (assign,nonatomic) NSUInteger counter;                                              //@synthesize counter=_counter - In the implementation block
@property (nonatomic,copy) NSString * title; 
@property (nonatomic,copy) NSString * subtitle; 
@property (nonatomic,copy) NSString * message; 
@property (nonatomic,retain) BBContent * content;                                                     //@synthesize content=_content - In the implementation block
@property (nonatomic,retain) BBContent * modalAlertContent;                                           //@synthesize modalAlertContent=_modalAlertContent - In the implementation block
@property (nonatomic,retain) BBContent * starkBannerContent;                                          //@synthesize starkBannerContent=_starkBannerContent - In the implementation block
@property (nonatomic,retain) BBSectionIcon * icon;                                                    //@synthesize icon=_icon - In the implementation block
@property (assign,nonatomic) BOOL hasEventDate;                                                       //@synthesize hasEventDate=_hasEventDate - In the implementation block
@property (nonatomic,retain) NSDate * date;                                                           //@synthesize date=_date - In the implementation block
@property (nonatomic,retain) NSDate * endDate;                                                        //@synthesize endDate=_endDate - In the implementation block
@property (nonatomic,retain) NSDate * recencyDate;                                                    //@synthesize recencyDate=_recencyDate - In the implementation block
@property (assign,nonatomic) NSInteger dateFormatStyle;                                               //@synthesize dateFormatStyle=_dateFormatStyle - In the implementation block
@property (assign,nonatomic) BOOL dateIsAllDay;                                                       //@synthesize dateIsAllDay=_dateIsAllDay - In the implementation block
@property (nonatomic,retain) NSTimeZone * timeZone;                                                   //@synthesize timeZone=_timeZone - In the implementation block
@property (nonatomic,retain) BBAccessoryIcon * accessoryIconMask;                                     //@synthesize accessoryIconMask=_accessoryIconMask - In the implementation block
@property (assign,nonatomic) BOOL clearable;                                                          //@synthesize clearable=_clearable - In the implementation block
@property (nonatomic,retain) BBSound * sound;                                                         //@synthesize sound=_sound - In the implementation block
@property (assign,nonatomic) BOOL turnsOnDisplay;                                                     //@synthesize turnsOnDisplay=_turnsOnDisplay - In the implementation block
@property (nonatomic,copy) BBAttachmentMetadata * primaryAttachment;                                  //@synthesize primaryAttachment=_primaryAttachment - In the implementation block
@property (nonatomic,copy) NSArray * additionalAttachments;                                           //@synthesize additionalAttachments=_additionalAttachments - In the implementation block
@property (assign,nonatomic) BOOL wantsFullscreenPresentation;                                        //@synthesize wantsFullscreenPresentation=_wantsFullscreenPresentation - In the implementation block
@property (assign,nonatomic) BOOL ignoresQuietMode;                                                   //@synthesize ignoresQuietMode=_ignoresQuietMode - In the implementation block
@property (nonatomic,copy) NSString * unlockActionLabelOverride;                                      //@synthesize unlockActionLabelOverride=_unlockActionLabelOverride - In the implementation block
@property (nonatomic,copy) BBAction * defaultAction; 
@property (nonatomic,copy) BBAction * alternateAction; 
@property (nonatomic,copy) BBAction * acknowledgeAction; 
@property (nonatomic,copy) BBAction * snoozeAction; 
@property (nonatomic,copy) BBAction * raiseAction; 
@property (nonatomic,copy) NSArray * buttons;                                                         //@synthesize buttons=_buttons - In the implementation block
@property (nonatomic,copy) NSMutableDictionary * actions;                                             //@synthesize actions=_actions - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * supplementaryActionsByLayout;                      //@synthesize supplementaryActionsByLayout=_supplementaryActionsByLayout - In the implementation block
@property (nonatomic,copy) NSSet * alertSuppressionContexts;                                          //@synthesize alertSuppressionContexts=_alertSuppressionContexts - In the implementation block
@property (assign,nonatomic) BOOL expiresOnPublisherDeath;                                            //@synthesize expiresOnPublisherDeath=_expiresOnPublisherDeath - In the implementation block
@property (nonatomic,retain) NSDictionary * context;                                                  //@synthesize context=_context - In the implementation block
@property (assign,nonatomic) BOOL usesExternalSync;                                                   //@synthesize usesExternalSync=_usesExternalSync - In the implementation block
@property (assign,getter=isLoading,nonatomic) BOOL lozading;                                           //@synthesize loading=_loading - In the implementation block
@property (nonatomic,copy) NSString * bulletinID;                                                     //@synthesize bulletinID=_bulletinID - In the implementation block
@property (nonatomic,retain) NSDate * lastInterruptDate;                                              //@synthesize lastInterruptDate=_lastInterruptDate - In the implementation block
@property (nonatomic,retain) NSDate * publicationDate;                                                //@synthesize publicationDate=_publicationDate - In the implementation block
@property (assign,nonatomic) BOOL hasPrivateContent;                                                  //@synthesize hasPrivateContent=_hasPrivateContent - In the implementation block
@property (nonatomic,copy) NSString * bulletinVersionID;                                              //@synthesize bulletinVersionID=_bulletinVersionID - In the implementation block
@property (nonatomic,retain) NSDate * expirationDate;                                                 //@synthesize expirationDate=_expirationDate - In the implementation block
@property (assign,nonatomic) NSUInteger expirationEvents;                                     //@synthesize expirationEvents=_expirationEvents - In the implementation block
@property (nonatomic,copy) BBAction * expireAction; 
@property (assign,nonatomic) NSUInteger realertCount_deprecated; 
@property (nonatomic,copy) NSSet * alertSuppressionAppIDs_deprecated; 
@property (nonatomic,retain) NSHashTable * observers;                                                 //@synthesize observers=_observers - In the implementation block
@property (nonatomic,retain) NSMutableArray * lifeAssertions;                                         //@synthesize lifeAssertions=_lifeAssertions - In the implementation block
@property (nonatomic,copy) NSString * parentSectionID;                                                //@synthesize parentSectionID=_parentSectionID - In the implementation block
@property (nonatomic,copy) NSString * universalSectionID;                                             //@synthesize universalSectionID=_universalSectionID - In the implementation block
@property (nonatomic,copy,readonly) NSString * publisherMatchID; 
+(BOOL)supportsSecureCoding;
+(void)vetSortDescriptor:(id)arg1 ;
+(id)validSortDescriptorsFromSortDescriptors:(id)arg1 ;
+(id)bulletinWithBulletin:(id)arg1 ;
+(id)bulletinReferenceDateFromDate:(id)arg1 ;
-(id)replacementObjectForCoder:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)setActions:(NSMutableDictionary *)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)setTitle:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(NSUInteger)hash;
-(id)description;
-(NSString *)section;
-(void)addObserver:(id)arg1 ;
-(NSMutableDictionary *)actions;
-(BBContent *)content;
-(NSString *)title;
-(void)setTimeZone:(NSTimeZone *)arg1 ;
-(NSDate *)date;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSDictionary *)context;
-(BBColor *)tintColor;
-(void)setDate:(NSDate *)arg1 ;
-(void)setIcon:(BBSectionIcon *)arg1 ;
-(NSString *)sectionID;
-(void)setSubtitle:(NSString *)arg1 ;
-(NSString *)subtitle;
-(void)setMessage:(NSString *)arg1 ;
-(NSString *)message;
-(void)setContext:(NSDictionary *)arg1 ;
-(BOOL)isLoading;
-(NSTimeZone *)timeZone;
-(void)setSound:(BBSound *)arg1 ;
-(BBSound *)sound;
-(id)shortDescription;
-(BBSectionIcon *)icon;
-(void)setSectionID:(NSString *)arg1 ;
-(id)awakeAfterUsingCoder:(id)arg1 ;
-(NSArray *)buttons;
-(NSDate *)expirationDate;
-(void)setExpirationDate:(NSDate *)arg1 ;
-(void)setSection:(NSString *)arg1 ;
-(NSString *)recordID;
-(void)setObservers:(NSHashTable *)arg1 ;
-(NSHashTable *)observers;
-(BBAction *)defaultAction;
-(void)setHasEventDate:(BOOL)arg1 ;
-(BOOL)hasEventDate;
-(void)setContent:(BBContent *)arg1 ;
-(BOOL)dateIsAllDay;
-(void)setDateIsAllDay:(BOOL)arg1 ;
-(NSDate *)recencyDate;
-(void)setRecencyDate:(NSDate *)arg1 ;
-(NSString *)bulletinID;
-(NSInteger)sectionSubtype;
-(BBContent *)modalAlertContent;
-(NSString *)publisherBulletinID;
-(NSArray *)intentIDs;
-(void)setBulletinID:(NSString *)arg1 ;
-(NSMutableArray *)lifeAssertions;
-(void)setLifeAssertions:(NSMutableArray *)arg1 ;
-(void)_fillOutCopy:(id)arg1 withZone:(NSZone*)arg2 ;
-(NSString *)bulletinVersionID;
-(NSString *)universalSectionID;
-(NSString *)dismissalID;
-(BBContent *)starkBannerContent;
-(BBAccessoryIcon *)accessoryIconMask;
-(BOOL)clearable;
-(BBAttachmentMetadata *)primaryAttachment;
-(NSArray *)additionalAttachments;
-(NSString *)unlockActionLabelOverride;
-(NSMutableDictionary *)supplementaryActionsByLayout;
-(NSUInteger)expirationEvents;
-(NSDate *)lastInterruptDate;
-(BOOL)usesExternalSync;
-(NSUInteger)realertCount_deprecated;
-(NSSet *)alertSuppressionAppIDs_deprecated;
-(id)_allActions;
-(id)_actionWithID:(id)arg1 fromActions:(id)arg2 ;
-(id)_allSupplementaryActions;
-(/*^block*/id)responseSendBlock;
-(id)_responseForAction:(id)arg1 ;
-(BBAction *)acknowledgeAction;
-(BBAction *)snoozeAction;
-(BBAction *)raiseAction;
-(BBAction *)expireAction;
-(id)firstValidObserver;
-(id)_actionKeyForType:(NSInteger)arg1 ;
-(void)setUniversalSectionID:(NSString *)arg1 ;
-(void)setSubsectionIDs:(NSSet *)arg1 ;
-(void)setThreadID:(NSString *)arg1 ;
-(void)setPeopleIDs:(NSArray *)arg1 ;
-(void)setAddressBookRecordID:(NSInteger)arg1 ;
-(void)setIntentIDs:(NSArray *)arg1 ;
-(void)setHasPrivateContent:(BOOL)arg1 ;
-(void)setModalAlertContent:(BBContent *)arg1 ;
-(void)setStarkBannerContent:(BBContent *)arg1 ;
-(void)setAccessoryIconMask:(BBAccessoryIcon *)arg1 ;
-(void)setTurnsOnDisplay:(BOOL)arg1 ;
-(void)setPrimaryAttachment:(BBAttachmentMetadata *)arg1 ;
-(void)setAdditionalAttachments:(NSArray *)arg1 ;
-(void)setUnlockActionLabelOverride:(NSString *)arg1 ;
-(void)setWantsFullscreenPresentation:(BOOL)arg1 ;
-(void)setIgnoresQuietMode:(BOOL)arg1 ;
-(void)setSupplementaryActionsByLayout:(NSMutableDictionary *)arg1 ;
-(void)setExpirationEvents:(NSUInteger)arg1 ;
-(void)setLastInterruptDate:(NSDate *)arg1 ;
-(void)setUsesExternalSync:(BOOL)arg1 ;
-(void)setBulletinVersionID:(NSString *)arg1 ;
-(void)setRealertCount_deprecated:(NSUInteger)arg1 ;
-(void)setAlertSuppressionAppIDs_deprecated:(NSSet *)arg1 ;
-(NSUInteger)numberOfAdditionalAttachmentsOfType:(NSInteger)arg1 ;
-(id)_safeDescription:(BOOL)arg1 ;
-(NSInteger)primaryAttachmentType;
-(NSUInteger)numberOfAdditionalAttachments;
-(BBAction *)alternateAction;
-(void)setAlternateAction:(BBAction *)arg1 ;
-(void)setAcknowledgeAction:(BBAction *)arg1 ;
-(void)setExpireAction:(BBAction *)arg1 ;
-(void)setSnoozeAction:(BBAction *)arg1 ;
-(void)setRaiseAction:(BBAction *)arg1 ;
-(id)responseForDefaultAction;
-(id)responseForAcknowledgeAction;
-(id)responseForSnoozeAction;
-(id)responseForRaiseAction;
-(id)responseForExpireAction;
-(id)actionForResponse:(id)arg1 ;
-(void)addLifeAssertion:(id)arg1 ;
-(void)setShowsMessagePreview:(BOOL)arg1 ;
-(id)safeDescription;
-(BOOL)expiresOnPublisherDeath;
-(void)setExpiresOnPublisherDeath:(BOOL)arg1 ;
-(BOOL)showsSubtitle;
-(BOOL)usesVariableLayout;
-(BOOL)orderSectionUsingRecencyDate;
-(BOOL)showsDateInFloatingLockScreenAlert;
-(NSString *)missedBannerDescriptionFormat;
-(NSString *)bannerAccessoryRemoteViewControllerClassName;
-(NSString *)bannerAccessoryRemoteServiceBundleIdentifier;
-(NSString *)secondaryContentRemoteViewControllerClassName;
-(NSString *)secondaryContentRemoteServiceBundleIdentifier;
-(BOOL)preservesUnlockActionCase;
-(BOOL)visuallyIndicatesWhenDateIsInFuture;
-(BOOL)preventLock;
-(BOOL)suppressesTitle;
-(BOOL)showsUnreadIndicatorForNoticesFeed;
-(BOOL)showsContactPhoto;
-(BOOL)playsSoundForModify;
-(NSUInteger)subtypePriority;
-(NSInteger)iPodOutAlertType;
-(NSSet *)alertSuppressionAppIDs;
-(id)_sectionParameters;
-(id)_sectionSubtypeParameters;
-(BOOL)suppressesMessageForPrivacy;
-(CGSize)composedAttachmentImageSizeWithObserver:(id)arg1 ;
-(void)setPublicationDate:(NSDate *)arg1 ;
-(NSDate *)publicationDate;
-(void)setButtons:(NSArray *)arg1 ;
-(id)syncHash;
-(void)setLoading:(BOOL)arg1 ;
-(void)setEndDate:(NSDate *)arg1 ;
-(NSString *)topic;
-(NSDate *)endDate;
-(id)actionWithIdentifier:(id)arg1 ;
-(id)responseForButtonActionAtIndex:(NSUInteger)arg1 ;
-(BOOL)showsMessagePreview;
-(void)setSectionSubtype:(NSInteger)arg1 ;
-(NSString *)parentSectionID;
-(void)setParentSectionID:(NSString *)arg1 ;
-(void)setRecordID:(NSString *)arg1 ;
-(void)setPublisherBulletinID:(NSString *)arg1 ;
-(void)setDefaultAction:(BBAction *)arg1 ;
-(NSString *)sectionDisplayName;
-(BBSectionIcon *)sectionIcon;
-(void)setClearable:(BOOL)arg1 ;
-(NSString *)threadID;
-(void)setDismissalID:(NSString *)arg1 ;
-(void)setCategoryID:(NSString *)arg1 ;
-(void)setDismissAction:(id)arg1 ;
-(NSInteger)dateFormatStyle;
-(void)setDateFormatStyle:(NSInteger)arg1 ;
-(NSUInteger)messageNumberOfLines;
-(id)responseForAction:(id)arg1 ;
-(NSSet *)subsectionIDs;
-(NSString *)publisherMatchID;
-(NSArray *)peopleIDs;
-(id)composedAttachmentImageWithObserver:(id)arg1 ;
-(NSSet *)alertSuppressionContexts;
-(void)setAlertSuppressionContexts:(NSSet *)arg1 ;
-(NSString *)fullAlternateActionLabel;
-(NSString *)fullUnlockActionLabel;
-(NSString *)alternateActionLabel;
-(NSString *)unlockActionLabel;
-(BOOL)ignoresQuietMode;
-(BOOL)inertWhenLocked;
-(BOOL)allowsAddingToLockScreenWhenUnlocked;
-(BOOL)allowsAutomaticRemovalFromLockScreen;
-(BOOL)prioritizeAtTopOfLockScreen;
-(BOOL)canBeSilencedByMenuButtonPress;
-(NSUInteger)realertCount;
-(BOOL)suppressesAlertsWhenAppIsActive;
-(BOOL)turnsOnDisplay;
-(BOOL)wantsFullscreenPresentation;
-(BOOL)preemptsPresentedAlert;
-(BOOL)sectionDisplaysCriticalBulletins;
-(BOOL)revealsAdditionalContentOnPresentation;
-(NSUInteger)privacySettings;
-(BOOL)hasPrivateContent;
-(BOOL)coalescesWhenLocked;
-(id)dismissAction;
-(id)silenceAction;
-(void)setSilenceAction:(id)arg1 ;
-(NSInteger)addressBookRecordID;
-(id)supplementaryActionsForLayout:(NSInteger)arg1 ;
-(id)supplementaryActions;
-(NSString *)categoryID;
-(NSUInteger)counter;
-(void)setCounter:(NSUInteger)arg1 ;
@end
