/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:54:20 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/CCUIButtonModuleDelegate-Protocol.h>

@interface CCUIButtonModule : NSObject {

	BOOL _enabled;
	BOOL _inoperative;
	id<CCUIButtonModuleDelegate> _delegate;
	UIViewController* _parentViewController;

}

@property (assign,getter=isEnabled,nonatomic) BOOL enabled;                               //@synthesize enabled=_enabled - In the implementation block
@property (assign,getter=isInoperative,nonatomic) BOOL inoperative;                       //@synthesize inoperative=_inoperative - In the implementation block
@property (assign,nonatomic) id<CCUIButtonModuleDelegate> delegate;                //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) UIViewController * parentViewController;              //@synthesize parentViewController=_parentViewController - In the implementation block
@property (nonatomic,readonly) NSArray * buttonActions; 
+(NSString *)identifier;
+(NSString *)displayName;
+(BOOL)isSupported:(int)arg1 ;
+(BOOL)isInternalButton;
+(BOOL)enabledByDefault;
-(void)setDelegate:(id<CCUIButtonModuleDelegate>)arg1 ;
-(id)description;
-(id<CCUIButtonModuleDelegate>)delegate;
-(int)state;
-(id)identifier;
-(UIViewController *)parentViewController;
-(void)deactivate;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)isEnabled;
-(void)setParentViewController:(UIViewController *)arg1 ;
-(void)_updateState;
-(void)activate;
-(NSString *)displayName;
-(BOOL)isRestricted;
-(void)setInoperative:(BOOL)arg1 ;
-(id)aggdKey;
-(BOOL)_toggleState;
-(id)glyphImageForState:(int)arg1 ;
-(BOOL)needsConfirmation;
-(void)confirmed:(BOOL)arg1 ;
-(id)confirmationAlertTitle;
-(id)confirmationAlertMessage;
-(id)glyphImageForState:(int)arg1 section:(int)arg2 ;
-(NSString *)unavailableText;
-(int)orbBehavior;
-(id)statusUpdate;
-(NSArray *)buttonActions;
-(BOOL)isInoperative;
-(void)_noteButtonStateDidChange;
-(void)_noteDisplayPropertiesDidChange;
-(void)toggleState;
-(void)warmup;
-(id)controlCenterSystemAgent;
-(void)cooldown;
@end
