

@interface IMDaemon : NSObject <IMDaemonProtocol, IMSystemMonitorListener> {

	NSRecursiveLock* _listenerLock;
	NSMutableArray* _listeners;
	NSMutableArray* _listenerLocalObjects;
	NSMutableArray* _listenerIDs;
	NSMutableArray* _listenerBundleIDs;
	NSMutableArray* _listenerCaps;
	NSMutableArray* _listenerVCCaps;
	NSMutableArray* _listenerProperties;
	NSMutableArray* _listenerAllowedServices;
	NSMutableArray* _listenerDeniedServices;
	IMRemoteObjectBroadcaster* _notifier;
	IMMessageContext* _currentMessageContext;
	id _stateMonitor;
	NSMutableArray* _autoLoggedOffAccounts;
	NSMutableArray* _autoAwayAccounts;
	NSMutableDictionary* _autoAccountsToStatusMessageMap;
	NSMutableDictionary* _properties;
	NSMutableDictionary* _persistentProperties;
	NSMutableDictionary* _invocationQueues;
	BOOL _switchedOut;
	BOOL _pendingCapabilitiesRefresh;
	BOOL _setupComplete;
	int _avToken;
	int _acToken;

}

@property (retain,readonly) NSMutableDictionary * properties;                              //@synthesize properties=_properties - In the implementation block
@property (retain,readonly) NSMutableDictionary * persistentProperties;                    //@synthesize 
@property (nonatomic,readonly) BOOL hasListeners; 
@property (nonatomic,readonly) BOOL hasChatListeners; 
@property (nonatomic,readonly) BOOL hasStatusManagingListeners; 
@property (nonatomic,readonly) BOOL hasMessagesListener; 
@property (nonatomic,readonly) BOOL isSetup; 
@property (nonatomic,readonly) unsigned long long vcCapabilities; 
-(void)autoLoginAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)autoReconnectAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)loginAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)logoutAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)holdBuddyUpdatesAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)resumeBuddyUpdatesAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)authenticateAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)registerAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)unregisterAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)requestGroupsAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)changeGroups:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)changeGroup:(id)arg1 changes:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)renameGroup:(id)arg1 to:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)acceptSubscriptionRequest:(BOOL)arg1 from:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)requestSubscriptionTo:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)startWatchingBuddy:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)stopWatchingBuddy:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)requestProperty:(id)arg1 ofPerson:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)setValue:(id)arg1 ofProperty:(id)arg2 ofPerson:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)updateAuthorizationCredentials:(id)arg1 token:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)joinChatID:(id)arg1 handleInfo:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 groupID:(id)arg5 joinProperties:(id)arg6 account:(id)arg7 messageContext:(id)arg8 ;
-(void)leaveChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)removeChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)invitePersonInfo:(id)arg1 withMessage:(id)arg2 toChatID:(id)arg3 identifier:(id)arg4 style:(unsigned char)arg5 account:(id)arg6 messageContext:(id)arg7 ;
-(void)removePersonInfo:(id)arg1 chatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 messageContext:(id)arg6 ;
-(void)declineInvitationToChatID:(id)arg1 identifier:(id)arg2 style:(unsigned char)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)sendMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 messageContext:(id)arg6 ;
-(void)sendReadReceiptForMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 messageContext:(id)arg6 ;
-(void)sendPlayedReceiptForMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 messageContext:(id)arg6 ;
-(void)sendSavedReceiptForMessage:(id)arg1 toChatID:(id)arg2 identifier:(id)arg3 style:(unsigned char)arg4 account:(id)arg5 messageContext:(id)arg6 ;
-(void)setProperties:(id)arg1 ofParticipant:(id)arg2 inChatID:(id)arg3 identifier:(id)arg4 style:(unsigned char)arg5 account:(id)arg6 messageContext:(id)arg7 ;
-(void)setBlockingMode:(unsigned)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)setAllowList:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)setBlockList:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)setBlockIdleStatus:(BOOL)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)passwordUpdatedAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)sendCommand:(id)arg1 withProperties:(id)arg2 toPerson:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)requestVCWithPerson:(id)arg1 properties:(id)arg2 conference:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)respondToVCInvitationWithPerson:(id)arg1 properties:(id)arg2 conference:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)cancelVCRequestWithPerson:(id)arg1 properties:(id)arg2 conference:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)sendCounterProposalToPerson:(id)arg1 properties:(id)arg2 conference:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)sendVCUpdate:(id)arg1 toPerson:(id)arg2 conference:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)sendAVMessageToPerson:(id)arg1 sessionID:(unsigned)arg2 type:(unsigned)arg3 userInfo:(id)arg4 conference:(id)arg5 account:(id)arg6 messageContext:(id)arg7 ;
-(void)relay:(id)arg1 sendInitateRequest:(id)arg2 toPerson:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)relay:(id)arg1 sendUpdate:(id)arg2 toPerson:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)relay:(id)arg1 sendCancel:(id)arg2 toPerson:(id)arg3 account:(id)arg4 messageContext:(id)arg5 ;
-(void)addAliases:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)removeAliases:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)validateAliases:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)unvalidateAliases:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)validateProfileAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)sendMappingPacket:(id)arg1 toHandle:(id)arg2 account:(id)arg3 messageContext:(id)arg4 ;
-(void)enrollDeviceForSMSRelay:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)unEnrollDeviceForSMSRelay:(id)arg1 account:(id)arg2 messageContext:(id)arg3 ;
-(void)enrollSelfDeviceForSMSRelay:(id)arg1 messageContext:(id)arg2 ;
-(void)_pidSuspended:(int)arg1 ;
-(id)listenerIDForLocalObject:(id)arg1 requireCapability:(unsigned)arg2 foundIndex:(unsigned long long*)arg3 ;
-(BOOL)hasChatListeners;
-(BOOL)hasStatusManagingListeners;
-(BOOL)hasMessagesListener;
-(void)_removeListener:(id)arg1 ;
-(void)_removeListenerObject:(id)arg1 ;
-(void)_removeLocalListenerObject:(id)arg1 ;
-(void)_postSetupToListener:(id)arg1 withContext:(id)arg2 messageContext:(id)arg3 ;
-(id)listenerWithName:(id)arg1 ;
-(void)removeListenerObject:(id)arg1 ;
-(void)removeLocalListenerObject:(id)arg1 ;
-(id)_setupInfoForListener:(id)arg1 withContext:(id)arg2 ;
-(BOOL)_setupListenerConnection:(id)arg1 listenerID:(id)arg2 pid:(int)arg3 setupInfo:(id)arg4 setupResponse:(id*)arg5 ;
-(void)setListenerCapabilities:(unsigned)arg1 messageContext:(id)arg2 ;
-(BOOL)_setupPlugInListenerConnection:(id)arg1 listenerID:(id)arg2 pid:(int)arg3 setupInfo:(id)arg4 setupResponse:(id*)arg5 ;
-(BOOL)daemonInterface:(id)arg1 shouldGrantAccessForPID:(int)arg2 auditToken:(SCD_Struct_IM0)arg3 portName:(id)arg4 listenerConnection:(id)arg5 setupInfo:(id)arg6 setupResponse:(id*)arg7 ;
-(BOOL)daemonInterface:(id)arg1 shouldGrantPlugInAccessForPID:(int)arg2 auditToken:(SCD_Struct_IM0)arg3 portName:(id)arg4 listenerConnection:(id)arg5 setupInfo:(id)arg6 setupResponse:(id*)arg7 ;
-(void)removeListener:(id)arg1 ;
-(void)remoteObjectDiedNotification:(id)arg1 ;
-(void)localObjectDiedNotification:(id)arg1 ;
-(BOOL)launchListenerForCapability:(unsigned)arg1 ;
-(void)postSetupToAllListeners;
-(BOOL)hasListeners;
-(void)autoLoginActiveAccountsIfNecessaryWithMessageContext:(id)arg1 ;
-(void)loginAllAccountsWithMessageContext:(id)arg1 ;
-(void)logoutAllAccountsWithMessageContext:(id)arg1 ;
-(void)addAccount:(id)arg1 defaults:(id)arg2 service:(id)arg3 messageContext:(id)arg4 ;
-(void)removeAccount:(id)arg1 messageContext:(id)arg2 ;
-(void)activateAccounts:(id)arg1 messageContext:(id)arg2 ;
-(void)deactivateAccounts:(id)arg1 messageContext:(id)arg2 ;
-(void)writeAccount:(id)arg1 defaults:(id)arg2 messageContext:(id)arg3 ;
-(void)requestBuddyPicturesAndPropertiesForAccount:(id)arg1 messageContext:(id)arg2 ;
-(BOOL)shouldLaunchTextAppForInvocation:(id)arg1 shouldDumpInvocation:(BOOL*)arg2 ;
-(BOOL)shouldLaunchVCAppForInvocation:(id)arg1 shouldDumpInvocation:(BOOL*)arg2 ;
-(BOOL)queue:(id)arg1 shouldInvoke:(id)arg2 ;
-(unsigned long long)queue:(id)arg1 optionsForInvocation:(id)arg2 ;
-(id)broadcasterWithID:(id)arg1 messageContext:(id)arg2 ;
-(id)broadcasterForTarget:(id)arg1 messageContext:(id)arg2 ;
-(id)broadcasterForAVInvitationListenersWithMessageContext:(id)arg1 ;
-(id)broadcasterForAVConferenceListenersWithMessageContext:(id)arg1 ;
-(id)broadcasterForACConferenceListenersWithMessageContext:(id)arg1 ;
-(BOOL)haveAnyListenersWithCap:(unsigned)arg1 ;
-(void)emptyBroadcasterInvocationQueue:(BOOL)arg1 forCapability:(unsigned)arg2 messageContext:(id)arg3 ;
-(id)_invocationQueueForCapability:(unsigned)arg1 create:(BOOL)arg2 ;
-(BOOL)_allowInvocationQueuesForListenerCapability:(unsigned)arg1 ;
-(id)_listenersWithCapabilities:(unsigned)arg1 allowedListenerIDs:(id)arg2 forService:(id)arg3 ;
-(BOOL)_alwaysUseInvocationQueuesForListenerCapability:(unsigned)arg1 ;
-(id)_broadcasterForListenersWithCapabilities:(unsigned)arg1 messageContext:(id)arg2 ;
-(id)broadcasterWithID:(id)arg1 forService:(id)arg2 messageContext:(id)arg3 ;
-(void)emptyBroadcasterInvocationQueues:(BOOL)arg1 messageContext:(id)arg2 ;
-(BOOL)shouldQueueBroadcasterInvocationsForCapability:(unsigned)arg1 ;
-(BOOL)haveAnyListenersWithID:(id)arg1 ;
-(id)broadcasterForService:(id)arg1 messageContext:(id)arg2 ;
-(id)broadcasterForTarget:(id)arg1 forService:(id)arg2 messageContext:(id)arg3 ;
-(id)broadcasterForListenersWithCapabilities:(unsigned)arg1 forService:(id)arg2 messageContext:(id)arg3 ;
-(id)broadcasterWithMessageContext:(id)arg1 ;
-(id)broadcasterForChatListenersWithMessageContext:(id)arg1 ;
-(id)broadcasterForChatDatabaseListenersWithMessageContext:(id)arg1 ;
-(id)broadcasterForListenersWithCapabilities:(unsigned)arg1 messageContext:(id)arg2 ;
-(BOOL)conferencingActive;
-(unsigned long long)vcCapabilitiesForListenerID:(id)arg1 ;
-(unsigned long long)_vcCapabilities;
-(BOOL)_conferencingAvailable;
-(BOOL)shouldBlockCamera;
-(BOOL)shouldBlockMic;
-(BOOL)shouldBlockARD;
-(void)setVCCapabilities:(unsigned long long)arg1 messageContext:(id)arg2 ;
-(void)requestPendingVCInvitesWithMessageContext:(id)arg1 ;
-(void)requestPendingACInvitesWithMessageContext:(id)arg1 ;
-(void)account:(id)arg1 avAction:(unsigned)arg2 withArguments:(id)arg3 toAVChat:(id)arg4 isVideo:(BOOL)arg5 messageContext:(id)arg6 ;
-(unsigned long long)vcCapabilities;
-(void)updateUnformattedID:(id)arg1 forBuddyID:(id)arg2 onService:(id)arg3 messageContext:(id)arg4 ;
-(void)loadMessageWithGUID:(id)arg1 queryID:(id)arg2 messageContext:(id)arg3 ;
-(void)loadHistoryForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 limit:(unsigned long long)arg4 beforeGUID:(id)arg5 afterGUID:(id)arg6 chatID:(id)arg7 queryID:(id)arg8 messageContext:(id)arg9 ;
-(void)loadAttachmentsForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 chatID:(id)arg4 queryID:(id)arg5 messageContext:(id)arg6 ;
-(void)deleteMessageWithGUIDs:(id)arg1 queryID:(id)arg2 messageContext:(id)arg3 ;
-(void)clearHistoryForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 beforeGUID:(id)arg4 afterGUID:(id)arg5 chatID:(id)arg6 queryID:(id)arg7 messageContext:(id)arg8 ;
-(void)cleanupAttachmentsWithMessageContext:(id)arg1 ;
-(void)loadFrequentRepliesForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 limit:(unsigned long long)arg4 chatID:(id)arg5 queryID:(id)arg6 messageContext:(id)arg7 ;
-(void)deleteFileTransferWithGUID:(id)arg1 messageContext:(id)arg2 ;
-(void)sendStandaloneFileTransfer:(id)arg1 messageContext:(id)arg2 ;
-(void)fileTransfer:(id)arg1 createdWithProperties:(id)arg2 messageContext:(id)arg3 ;
-(void)fileTransfer:(id)arg1 updatedWithProperties:(id)arg2 messageContext:(id)arg3 ;
-(void)fileTransfer:(id)arg1 acceptedWithPath:(id)arg2 autoRename:(BOOL)arg3 overwrite:(BOOL)arg4 messageContext:(id)arg5 ;
-(void)fileTransferStopped:(id)arg1 messageContext:(id)arg2 ;
-(void)fileTransferRemoved:(id)arg1 messageContext:(id)arg2 ;
-(void)markPlayedForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 message:(id)arg4 messageContext:(id)arg5 ;
-(void)markSavedForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 message:(id)arg4 messageContext:(id)arg5 ;
-(void)storeItem:(id)arg1 inChatGUID:(id)arg2 messageContext:(id)arg3 ;
-(void)markReadForIDs:(id)arg1 style:(unsigned char)arg2 onServices:(id)arg3 messages:(id)arg4 messageContext:(id)arg5 ;
-(void)markReadForMessageGUID:(id)arg1 messageContext:(id)arg2 ;
-(void)markPlayedForMessageGUID:(id)arg1 messageContext:(id)arg2 ;
-(void)markSavedForMessageGUID:(id)arg1 messageContext:(id)arg2 ;
-(void)removeChat:(id)arg1 messageContext:(id)arg2 ;
-(void)chat:(id)arg1 updateDisplayName:(id)arg2 messageContext:(id)arg3 ;
-(void)chat:(id)arg1 updateProperties:(id)arg2 messageContext:(id)arg3 ;
-(void)silenceChat:(id)arg1 untilDate:(id)arg2 messageContext:(id)arg3 ;
-(void)updateMessage:(id)arg1 messageContext:(id)arg2 ;
-(void)requestPendingMessagesWithMessageContext:(id)arg1 ;
-(void)_postAliveNotification;
-(void)_setupComplete;
-(void)_loadAccounts;
-(BOOL)_loadDaemon;
-(void)_loadServices;
-(void)_terminate;
-(void)_reallyRefreshServiceCapabilities;
-(void)_property:(id)arg1 changedFrom:(id)arg2 to:(id)arg3 ;
-(void)_setValue:(id)arg1 ofProperty:(id)arg2 messageContext:(id)arg3 ;
-(void)_setValue:(id)arg1 ofPersistentProperty:(id)arg2 listenerID:(id)arg3 messageContext:(id)arg4 ;
-(void)setCurrentMessageContext:(IMMessageContext *)arg1 ;
-(void)_deviceCapabilitiesChanged;
-(void)_importFinished;
-(void)changeMyStatus:(id)arg1 forAccount:(id)arg2 messageContext:(id)arg3 ;
-(void)pruneProperties;
-(void)setValue:(id)arg1 ofProperty:(id)arg2 messageContext:(id)arg3 ;
-(void)_setValue:(id)arg1 ofPersistentProperty:(id)arg2 messageContext:(id)arg3 ;
-(void)setValue:(id)arg1 ofPersistentProperty:(id)arg2 messageContext:(id)arg3 ;
-(void)logState;
-(void)logInfo;
-(void)refreshBundleIDs;
-(void)terminate;
-(void)dealloc;
-(id)init;
-(NSMutableDictionary *)properties;
-(void)systemWillShutdown;
-(void)shutdown;
-(BOOL)isSetup;
-(id)valueOfProperty:(id)arg1 ;
-(id)valueOfPersistentProperty:(id)arg1 ;
-(NSMutableDictionary *)persistentProperties;
-(IMMessageContext *)currentMessageContext;
-(void)refreshServiceCapabilities;
-(void)_setValue:(id)arg1 ofPersistentProperty:(id)arg2 ;
@end
